import SwiftUI

/// Left sidebar of the Memory home view. Renders four blocks:
///   1. Group-by selector (Type / Entity / Tag).
///   2. Topics list, generated by the chosen `groupBy`.
///   3. Scopes filter (user / agent / project) as multi-select toggles.
///   4. Captures + Settings entries.
///
/// The sidebar is a pure presentation: it derives all of its rows from
/// the `notes` it gets, plus the ClawJS Memory `stats`. The home view
/// owns the selection state via the bindings.
struct MemorySidebar: View {

    enum GroupBy: String, CaseIterable, Identifiable {
        case type
        case entity
        case tag

        var id: String { rawValue }
        var label: String {
            switch self {
            case .type: return "Type"
            case .entity: return "Entity"
            case .tag: return "Tag"
            }
        }
    }

    enum TopicID: Equatable, Hashable {
        case all
        case type(String)
        case entity(String)
        case tag(String)
    }

    enum ScopeAxis: String, CaseIterable, Identifiable {
        case user, agent, project
        var id: String { rawValue }
    }

    @Binding var groupBy: GroupBy
    @Binding var selectedTopic: TopicID?
    @Binding var selectedScopes: Set<ScopeAxis>
    let notes: [ClawJSMemoryClient.MemoryNote]
    let stats: ClawJSMemoryClient.MemoryStatsResponse?
    let pendingCaptures: Int
    let onOpenCaptures: () -> Void
    let onOpenSettings: () -> Void

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 14) {
                groupByPicker
                topicsSection
                scopesSection
                bottomActions
            }
            .padding(.horizontal, 8)
            .padding(.vertical, 12)
        }
        .background(Color.clear)
    }

    // MARK: - Group-by selector

    private var groupByPicker: some View {
        VStack(alignment: .leading, spacing: 6) {
            Text("Group by")
                .font(BodyFont.system(size: 10.5, wght: 600))
                .foregroundColor(.white.opacity(0.55))
                .textCase(.uppercase)
                .padding(.leading, 4)
            Picker("Group by", selection: $groupBy) {
                ForEach(GroupBy.allCases) { item in
                    Text(item.label).tag(item)
                }
            }
            .pickerStyle(.segmented)
            .controlSize(.small)
            .padding(.horizontal, 2)
        }
    }

    // MARK: - Topics

    private var topicsSection: some View {
        VStack(alignment: .leading, spacing: 2) {
            sectionHeader("Topics")
            row(
                title: "All",
                count: notes.count,
                isSelected: selectedTopic == nil || selectedTopic == .all,
                onTap: { selectedTopic = .all }
            )
            ForEach(topicEntries, id: \.0) { (idString, label, count, topicId) in
                row(
                    title: label,
                    count: count,
                    isSelected: selectedTopic == topicId,
                    onTap: { selectedTopic = topicId }
                )
            }
            if topicEntries.isEmpty {
                Text("No memories yet.")
                    .font(BodyFont.system(size: 11.5, wght: 400))
                    .foregroundColor(.white.opacity(0.4))
                    .padding(.leading, 10)
                    .padding(.top, 4)
            }
        }
    }

    private var topicEntries: [(String, String, Int, TopicID)] {
        switch groupBy {
        case .type:
            var counts: [String: Int] = [:]
            for note in notes {
                let key = (note.semanticKind?.isEmpty == false ? note.semanticKind! : note.type)
                counts[key, default: 0] += 1
            }
            return counts
                .sorted { $0.value > $1.value }
                .map { ($0.key, $0.key.capitalizedFriendly, $0.value, .type($0.key)) }
        case .entity:
            var counts: [String: Int] = [:]
            for note in notes {
                for (key, value) in note.frontmatter {
                    if key == "id" || key == "slug" || key == "tags" { continue }
                    if let id = stringRef(value), id.hasPrefix("ent_") {
                        counts[id, default: 0] += 1
                    }
                    if case .array(let array) = value {
                        for item in array {
                            if let id = stringRef(item), id.hasPrefix("ent_") {
                                counts[id, default: 0] += 1
                            }
                        }
                    }
                }
            }
            return counts
                .sorted { $0.value > $1.value }
                .map { ($0.key, $0.key, $0.value, .entity($0.key)) }
        case .tag:
            var counts: [String: Int] = [:]
            for note in notes {
                for tag in note.tags {
                    counts[tag, default: 0] += 1
                }
            }
            return counts
                .sorted { $0.value > $1.value }
                .map { ($0.key, "#\($0.key)", $0.value, .tag($0.key)) }
        }
    }

    private func stringRef(_ value: AnyJSON) -> String? {
        if case .string(let s) = value { return s }
        return nil
    }

    // MARK: - Scopes

    private var scopesSection: some View {
        VStack(alignment: .leading, spacing: 2) {
            sectionHeader("Scopes")
            ForEach(ScopeAxis.allCases) { axis in
                let isOn = selectedScopes.contains(axis)
                row(
                    title: scopeLabel(axis),
                    count: scopeCount(axis),
                    isSelected: isOn,
                    onTap: {
                        if isOn { selectedScopes.remove(axis) }
                        else { selectedScopes.insert(axis) }
                    },
                    leadingIcon: isOn ? "checkmark.circle.fill" : "circle"
                )
            }
        }
    }

    private func scopeLabel(_ axis: ScopeAxis) -> String {
        switch axis {
        case .user: return "User scope"
        case .agent: return "Agent scope"
        case .project: return "Project scope"
        }
    }

    private func scopeCount(_ axis: ScopeAxis) -> Int {
        switch axis {
        case .user: return notes.filter { $0.scopeUser != nil }.count
        case .agent: return notes.filter { $0.scopeAgent != nil }.count
        case .project: return notes.filter { $0.scopeProject != nil }.count
        }
    }

    // MARK: - Bottom actions

    private var bottomActions: some View {
        VStack(alignment: .leading, spacing: 2) {
            sectionHeader("Workspace")
            row(
                title: "Captures",
                count: pendingCaptures,
                isSelected: false,
                onTap: onOpenCaptures,
                leadingIcon: "tray"
            )
            row(
                title: "Settings",
                count: nil,
                isSelected: false,
                onTap: onOpenSettings,
                leadingIcon: "gear"
            )
        }
    }

    // MARK: - Helpers

    private func sectionHeader(_ title: String) -> some View {
        Text(title)
            .font(BodyFont.system(size: 10.5, wght: 600))
            .foregroundColor(.white.opacity(0.55))
            .textCase(.uppercase)
            .padding(.leading, 8)
            .padding(.top, 6)
    }

    private func row(
        title: String,
        count: Int?,
        isSelected: Bool,
        onTap: @escaping () -> Void,
        leadingIcon: String? = nil
    ) -> some View {
        MemorySidebarRow(
            title: title,
            count: count,
            isSelected: isSelected,
            leadingIcon: leadingIcon,
            onTap: onTap
        )
    }
}

private struct MemorySidebarRow: View {
    let title: String
    let count: Int?
    let isSelected: Bool
    let leadingIcon: String?
    let onTap: () -> Void
    @State private var hovered = false

    var body: some View {
        Button(action: onTap) {
            HStack(spacing: 8) {
                if let icon = leadingIcon {
                    Image(systemName: icon)
                        .font(.system(size: 11, weight: .medium))
                        .foregroundColor(iconColor)
                        .frame(width: 14)
                }
                Text(title)
                    .font(BodyFont.system(size: 12.5, wght: 500))
                    .foregroundColor(labelColor)
                    .lineLimit(1)
                Spacer(minLength: 4)
                if let count {
                    Text(String(count))
                        .font(BodyFont.system(size: 11, wght: 500))
                        .foregroundColor(.white.opacity(isSelected ? 0.7 : 0.4))
                }
            }
            .padding(.horizontal, 8)
            .padding(.vertical, 5)
            .contentShape(Rectangle())
            .background(
                RoundedRectangle(cornerRadius: 7, style: .continuous)
                    .fill(backgroundFill)
            )
            .animation(.easeOut(duration: 0.10), value: hovered)
        }
        .buttonStyle(.plain)
        .onHover { hovered = $0 }
    }

    private var iconColor: Color {
        if isSelected { return .white }
        return Color(white: hovered ? 0.85 : 0.65)
    }

    private var labelColor: Color {
        isSelected ? .white : Color(white: hovered ? 0.95 : 0.85)
    }

    private var backgroundFill: Color {
        if isSelected { return Color.white.opacity(0.08) }
        if hovered    { return Color.white.opacity(0.04) }
        return .clear
    }
}

private extension String {
    var capitalizedFriendly: String {
        replacingOccurrences(of: "_", with: " ").capitalized
    }
}
