// Generated by scripts/generate-surface-route-registry.mjs from docs/surface-route-registry.manifest.json.
// Do not edit by hand.

import Foundation

enum SurfaceRouteModule: String, Equatable, Hashable, CaseIterable {
    case core
    case protected
    case apps
    case automation
    case data
    case drive
    case time
    case skills
    case iot
    case design
    case agents
    case publishing
    case life
    case network
}

struct SurfaceRouteMetadata: Equatable {
    var routeCase: String
    var id: String
    var module: SurfaceRouteModule
    var criticality: SurfaceRouteCriticality
    var routeTarget: String?
    var supportsVariantDefault: Bool
    var timeoutSeconds: TimeInterval?
    var requiresIndependentDegradation: Bool
    var readinessMode: SurfaceRouteReadinessMode
    var dependencies: Set<SurfaceRouteDependency>

    var descriptor: SurfaceRouteDescriptor {
        SurfaceRouteDescriptor(
            id: id,
            criticality: criticality,
            routeTarget: routeTarget,
            supportsVariantDefault: supportsVariantDefault,
            timeoutSeconds: timeoutSeconds,
            requiresIndependentDegradation: requiresIndependentDegradation,
            dependencies: dependencies
        )
    }
}

enum SurfaceRouteMetadataCatalog {
    static let manifestVersion = 1
    static let manifestRouteCases: Set<String> = ["home", "search", "plugins", "automations", "project", "app", "appsHome", "chat", "settings", "rescue", "secretsHome", "databaseHome", "databaseWorkbench", "databaseCollection", "memoryHome", "indexHome", "macCare", "marketplaceHome", "driveAdmin", "drivePhotos", "driveDocuments", "driveRecent", "driveFolder", "calendarHome", "contactsHome", "networkControl", "skills", "skillDetail", "iotHome", "iotDeviceDetail", "designStylesHome", "designStyleDetail", "designTemplatesHome", "designTemplateDetail", "designReferencesHome", "designEditor", "agentsHome", "agentDetail", "personalitiesHome", "personalityDetail", "skillCollectionsHome", "skillCollectionDetail", "connectionsHome", "connectionDetail", "publishingHome", "publishingComposer", "publishingChannels", "lifeHome", "lifeVertical", "lifeSettings"]
    static let manifestModuleKinds: Set<String> = ["core", "protected", "apps", "automation", "data", "drive", "time", "skills", "iot", "design", "agents", "publishing", "life", "network"]
    static let manifestDependencyKinds: Set<String> = ["languageModels", "searchIndex", "databaseBackfill", "customApps", "connectors", "downloads", "externalProviders"]
    static let manifestReadinessModeKinds: Set<String> = ["immediateAfterFirstRender", "childReported"]
    static let manifestDirectChildReportedRouteCases: Set<String> = ["app"]

    static func metadata(for route: SidebarRoute) -> SurfaceRouteMetadata {
        switch route {
        case .home:
            return SurfaceRouteMetadata(
                routeCase: "home",
                id: "home",
                module: .core,
                criticality: .core,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: nil,
                requiresIndependentDegradation: false,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .search:
            return SurfaceRouteMetadata(
                routeCase: "search",
                id: "search",
                module: .core,
                criticality: .core,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: nil,
                requiresIndependentDegradation: false,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .plugins:
            return SurfaceRouteMetadata(
                routeCase: "plugins",
                id: "plugins",
                module: .automation,
                criticality: .extensionSurface,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .automations:
            return SurfaceRouteMetadata(
                routeCase: "automations",
                id: "automations",
                module: .automation,
                criticality: .extensionSurface,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .project:
            return SurfaceRouteMetadata(
                routeCase: "project",
                id: "project",
                module: .core,
                criticality: .core,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: nil,
                requiresIndependentDegradation: false,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .app(let id):
            return SurfaceRouteMetadata(
                routeCase: "app",
                id: "app:\(id.uuidString)",
                module: .apps,
                criticality: .extensionSurface,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .childReported,
                dependencies: [.customApps, .downloads]
            )
        case .appsHome:
            return SurfaceRouteMetadata(
                routeCase: "appsHome",
                id: "apps",
                module: .apps,
                criticality: .extensionSurface,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.customApps, .downloads]
            )
        case .chat(let id):
            return SurfaceRouteMetadata(
                routeCase: "chat",
                id: "chat:\(id.uuidString)",
                module: .core,
                criticality: .core,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: nil,
                requiresIndependentDegradation: false,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .settings:
            return SurfaceRouteMetadata(
                routeCase: "settings",
                id: "settings",
                module: .core,
                criticality: .core,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: nil,
                requiresIndependentDegradation: false,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .rescue:
            return SurfaceRouteMetadata(
                routeCase: "rescue",
                id: "rescue",
                module: .core,
                criticality: .core,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: nil,
                requiresIndependentDegradation: false,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .secretsHome:
            return SurfaceRouteMetadata(
                routeCase: "secretsHome",
                id: "secrets",
                module: .protected,
                criticality: .protected,
                routeTarget: normalizedRouteTarget("secrets"),
                supportsVariantDefault: true,
                timeoutSeconds: 8,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .databaseHome:
            return SurfaceRouteMetadata(
                routeCase: "databaseHome",
                id: "database",
                module: .data,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("database"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.databaseBackfill]
            )
        case .databaseWorkbench:
            return SurfaceRouteMetadata(
                routeCase: "databaseWorkbench",
                id: "database-workbench",
                module: .data,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("database-workbench"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.databaseBackfill]
            )
        case .databaseCollection(let name):
            return SurfaceRouteMetadata(
                routeCase: "databaseCollection",
                id: "database:\(name)",
                module: .data,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("database/\(name)"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.databaseBackfill]
            )
        case .memoryHome:
            return SurfaceRouteMetadata(
                routeCase: "memoryHome",
                id: "memory",
                module: .data,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("memory"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.searchIndex]
            )
        case .indexHome:
            return SurfaceRouteMetadata(
                routeCase: "indexHome",
                id: "index",
                module: .data,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("index"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.searchIndex]
            )
        case .macCare:
            return SurfaceRouteMetadata(
                routeCase: "macCare",
                id: "mac-care",
                module: .data,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("mac-care"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .marketplaceHome:
            return SurfaceRouteMetadata(
                routeCase: "marketplaceHome",
                id: "marketplace",
                module: .apps,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("marketplace"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .driveAdmin:
            return SurfaceRouteMetadata(
                routeCase: "driveAdmin",
                id: "drive",
                module: .drive,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("drive"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.connectors, .downloads]
            )
        case .drivePhotos:
            return SurfaceRouteMetadata(
                routeCase: "drivePhotos",
                id: "drive:photos",
                module: .drive,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("drive/photos"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.connectors, .downloads]
            )
        case .driveDocuments:
            return SurfaceRouteMetadata(
                routeCase: "driveDocuments",
                id: "drive:documents",
                module: .drive,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("drive/documents"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.connectors, .downloads]
            )
        case .driveRecent:
            return SurfaceRouteMetadata(
                routeCase: "driveRecent",
                id: "drive:recent",
                module: .drive,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("drive/recent"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.connectors, .downloads]
            )
        case .driveFolder(let id):
            return SurfaceRouteMetadata(
                routeCase: "driveFolder",
                id: "drive:folder:\(id)",
                module: .drive,
                criticality: .extensionSurface,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.connectors, .downloads]
            )
        case .calendarHome:
            return SurfaceRouteMetadata(
                routeCase: "calendarHome",
                id: "calendar",
                module: .time,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("calendar"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.connectors, .downloads]
            )
        case .contactsHome:
            return SurfaceRouteMetadata(
                routeCase: "contactsHome",
                id: "contacts",
                module: .time,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("contacts"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.connectors, .downloads]
            )
        case .networkControl:
            return SurfaceRouteMetadata(
                routeCase: "networkControl",
                id: "network-control",
                module: .network,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("network-control"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.connectors]
            )
        case .skills:
            return SurfaceRouteMetadata(
                routeCase: "skills",
                id: "skills",
                module: .skills,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("skills"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .skillDetail(let slug):
            return SurfaceRouteMetadata(
                routeCase: "skillDetail",
                id: "skill:\(slug)",
                module: .skills,
                criticality: .extensionSurface,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .iotHome:
            return SurfaceRouteMetadata(
                routeCase: "iotHome",
                id: "iot",
                module: .iot,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("iot"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.connectors, .externalProviders]
            )
        case .iotDeviceDetail(let id):
            return SurfaceRouteMetadata(
                routeCase: "iotDeviceDetail",
                id: "iot:device:\(id)",
                module: .iot,
                criticality: .extensionSurface,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.connectors, .externalProviders]
            )
        case .designStylesHome:
            return SurfaceRouteMetadata(
                routeCase: "designStylesHome",
                id: "design:styles",
                module: .design,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("design/styles"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .designStyleDetail(let id):
            return SurfaceRouteMetadata(
                routeCase: "designStyleDetail",
                id: "design:style:\(id)",
                module: .design,
                criticality: .extensionSurface,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .designTemplatesHome:
            return SurfaceRouteMetadata(
                routeCase: "designTemplatesHome",
                id: "design:templates",
                module: .design,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("design/templates"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .designTemplateDetail(let id):
            return SurfaceRouteMetadata(
                routeCase: "designTemplateDetail",
                id: "design:template:\(id)",
                module: .design,
                criticality: .extensionSurface,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .designReferencesHome:
            return SurfaceRouteMetadata(
                routeCase: "designReferencesHome",
                id: "design:references",
                module: .design,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("design/references"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .designEditor(let id):
            return SurfaceRouteMetadata(
                routeCase: "designEditor",
                id: "design:editor:\(id)",
                module: .design,
                criticality: .extensionSurface,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .agentsHome:
            return SurfaceRouteMetadata(
                routeCase: "agentsHome",
                id: "agents",
                module: .agents,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("agents"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.languageModels]
            )
        case .agentDetail(let id):
            return SurfaceRouteMetadata(
                routeCase: "agentDetail",
                id: "agent:\(id)",
                module: .agents,
                criticality: .extensionSurface,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.languageModels]
            )
        case .personalitiesHome:
            return SurfaceRouteMetadata(
                routeCase: "personalitiesHome",
                id: "personalities",
                module: .agents,
                criticality: .extensionSurface,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.languageModels]
            )
        case .personalityDetail(let id):
            return SurfaceRouteMetadata(
                routeCase: "personalityDetail",
                id: "personality:\(id)",
                module: .agents,
                criticality: .extensionSurface,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.languageModels]
            )
        case .skillCollectionsHome:
            return SurfaceRouteMetadata(
                routeCase: "skillCollectionsHome",
                id: "skill-collections",
                module: .skills,
                criticality: .extensionSurface,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .skillCollectionDetail(let id):
            return SurfaceRouteMetadata(
                routeCase: "skillCollectionDetail",
                id: "skill-collection:\(id)",
                module: .skills,
                criticality: .extensionSurface,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .connectionsHome:
            return SurfaceRouteMetadata(
                routeCase: "connectionsHome",
                id: "connections",
                module: .agents,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("connections"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.connectors, .downloads]
            )
        case .connectionDetail(let id):
            return SurfaceRouteMetadata(
                routeCase: "connectionDetail",
                id: "connection:\(id)",
                module: .agents,
                criticality: .extensionSurface,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.connectors, .downloads]
            )
        case .publishingHome:
            return SurfaceRouteMetadata(
                routeCase: "publishingHome",
                id: "publishing",
                module: .publishing,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("publishing"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.connectors, .externalProviders]
            )
        case .publishingComposer(let prefill, let scheduleAt):
            return SurfaceRouteMetadata(
                routeCase: "publishingComposer",
                id: "publishing:composer:\(prefill?.hashValue ?? 0):\(scheduleAt?.timeIntervalSince1970 ?? 0)",
                module: .publishing,
                criticality: .extensionSurface,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.connectors, .externalProviders]
            )
        case .publishingChannels:
            return SurfaceRouteMetadata(
                routeCase: "publishingChannels",
                id: "publishing:channels",
                module: .publishing,
                criticality: .extensionSurface,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: [.connectors, .externalProviders]
            )
        case .lifeHome:
            return SurfaceRouteMetadata(
                routeCase: "lifeHome",
                id: "life",
                module: .life,
                criticality: .extensionSurface,
                routeTarget: normalizedRouteTarget("life"),
                supportsVariantDefault: true,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .lifeVertical(let id):
            return SurfaceRouteMetadata(
                routeCase: "lifeVertical",
                id: "life:\(id)",
                module: .life,
                criticality: .extensionSurface,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        case .lifeSettings:
            return SurfaceRouteMetadata(
                routeCase: "lifeSettings",
                id: "life:settings",
                module: .life,
                criticality: .extensionSurface,
                routeTarget: nil,
                supportsVariantDefault: false,
                timeoutSeconds: 5,
                requiresIndependentDegradation: true,
                readinessMode: .immediateAfterFirstRender,
                dependencies: []
            )
        }
    }

    private static func normalizedRouteTarget(_ routeTarget: String) -> String {
        routeTarget.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
    }
}

extension SidebarRoute {
    var surfaceRouteMetadata: SurfaceRouteMetadata {
        SurfaceRouteMetadataCatalog.metadata(for: self)
    }
}
