export const TOP_LEVEL_FRAME_KEYS = ["schemaVersion", "type"] as const;

export const ALLOWED_PAYLOAD_KEYS = {
  auth: ["token", "deviceName", "clientKind", "clientId", "installationId", "deviceId"],
  listSessions: [],
  openSession: ["sessionId", "limit"],
  loadOlderMessages: ["sessionId", "beforeMessageId", "limit"],
  sendMessage: ["sessionId", "text", "attachments"],
  newSession: ["sessionId", "text", "attachments"],
  interruptTurn: ["sessionId"],
  editPrompt: ["sessionId", "messageId", "text"],
  archiveSession: ["sessionId"],
  unarchiveSession: ["sessionId"],
  pinSession: ["sessionId"],
  unpinSession: ["sessionId"],
  renameSession: ["sessionId", "title"],
  pairingStart: [],
  listProjects: [],
  readFile: ["path"],
  transcribeAudio: ["requestId", "audioBase64", "mimeType", "language"],
  requestAudio: ["audioId"],
  requestGeneratedImage: ["path"],
  requestRolloutAttachment: ["attachmentId"],
  requestRateLimits: [],
  requestClawJSServiceStatuses: [],
  authOk: ["hostDisplayName"],
  authFailed: ["reason"],
  versionMismatch: ["serverVersion"],
  sessionsSnapshot: ["sessions"],
  sessionUpdated: ["session"],
  messagesSnapshot: ["sessionId", "messages", "hasMore"],
  messagesPage: ["sessionId", "messages", "hasMore"],
  messageAppended: ["sessionId", "message"],
  messageStreaming: ["sessionId", "messageId", "content", "reasoningText", "finished"],
  errorEvent: ["code", "message"],
  pairingPayload: ["qrJson", "token", "shortCode"],
  projectsSnapshot: ["projects"],
  fileSnapshot: ["path", "content", "isMarkdown", "error"],
  transcriptionResult: ["requestId", "text", "errorMessage"],
  audioSnapshot: ["audioId", "audioBase64", "mimeType", "errorMessage"],
  generatedImageSnapshot: ["path", "dataBase64", "mimeType", "errorMessage"],
  rolloutAttachmentSnapshot: ["attachmentId", "dataBase64", "mimeType", "errorMessage"],
  bridgeState: ["state", "chatCount", "message"],
  rateLimitsSnapshot: ["rateLimits", "rateLimitsByLimitId"],
  rateLimitsUpdated: ["rateLimits", "rateLimitsByLimitId"],
  clawJSServiceStatusesSnapshot: ["services"],
  clawJSServiceStatusUpdated: ["service"],
  audioRegister: ["requestId", "request"],
  audioAttachTranscript: ["requestId", "audioId", "transcript"],
  audioGet: ["requestId", "audioId", "appId"],
  audioGetBytes: ["requestId", "audioId", "appId"],
  audioList: ["requestId", "filter"],
  audioDelete: ["requestId", "audioId", "appId"],
  audioRegisterResult: ["requestId", "asset", "errorMessage"],
  audioAttachTranscriptResult: ["requestId", "transcript", "errorMessage"],
  audioGetResult: ["requestId", "asset", "errorMessage"],
  audioBytesResult: ["requestId", "audioBase64", "mimeType", "durationMs", "errorMessage"],
  audioListResult: ["requestId", "list", "errorMessage"],
  audioDeleteResult: ["requestId", "deleted", "errorMessage"],
} as const satisfies Record<string, readonly string[]>;

export type BridgePayloadFrameType = keyof typeof ALLOWED_PAYLOAD_KEYS;
