package com.example.clawix.android.icons

/**
 * Subset of the Lucide icon font's PUA codepoints used by the iPhone
 * app. The codepoints come from
 * https://lucide.dev/icons/<name> "Copy unicode" view; they live in the
 * Private Use Area between U+E000 and U+F8FF.
 *
 * If a glyph is missing here, add it; never call `LucideIcon` with a
 * raw codepoint, the indirection lets the compiler catch typos.
 */
enum class LucideGlyph(val codepoint: Int) {
    Search(0xea21),
    X(0xea0f),
    Plus(0xe9b3),
    Check(0xe9b8),
    ChevronDown(0xe9c1),
    ChevronUp(0xe9c4),
    ChevronLeft(0xe9c2),
    ChevronRight(0xe9c3),
    ArrowLeft(0xe991),
    ArrowRight(0xe994),
    ArrowUp(0xe996),
    ArrowDown(0xe98e),
    Send(0xea1f),
    Mic(0xeac6),
    MicOff(0xeac7),
    Camera(0xea98),
    Image(0xeabc),
    Images(0xeabd),
    ImageOff(0xeabe),
    Paperclip(0xeb0a),
    Trash2(0xeae1),
    Settings(0xea22),
    Globe(0xeaa6),
    Folder(0xeaa3),
    FolderOpen(0xeaa4),
    Star(0xea25),
    Clock(0xea03),
    List(0xeab0),
    ListChecks(0xeab1),
    Key(0xeac0),
    Link(0xeac4),
    Laptop(0xeaaa),
    Scan(0xea1d),
    QrCode(0xeb1d),
    Pin(0xeb13),
    Pencil(0xea14),
    Terminal(0xea7d),
    FileQuestionMark(0xeaa1),
    Inbox(0xeaae),
    Play(0xea18),
    Pause(0xea11),
    AudioWaveform(0xeb31),
    AudioLines(0xeb30),
    CircleAlert(0xe9d2),
    CircleCheck(0xe9d4),
    CircleX(0xe9d8),
    Eye(0xea7c),
    EyeOff(0xea7d),
    Glasses(0xeaa5),
    StopCircle(0xeb27),
    Bot(0xea96),
    User(0xea2a),
    MessageCircle(0xeac9),
    Hash(0xeaa8),
    Lock(0xeac3),
    Unlock(0xeac5),
    Wifi(0xea2c),
    WifiOff(0xea2d),
    Refresh(0xea1c),
    Download(0xea05),
    Share2(0xea24),
    Archive(0xe98d),
    ArrowUpRight(0xe99a),
    Copy(0xe9d6),
    Tornado(0xea29),
    Drama(0xea08),
    Edit(0xea0a),
    Edit2(0xea0b),
    Edit3(0xea0c),
    AppWindow(0xea93),
    Server(0xea20),
}
