import ClawHostKit
import Foundation

typealias NativeMacActionRequest = MacControlActionRequest
typealias NativeMacActionPlan = MacControlActionPlan
typealias NativeMacActionReceipt = MacControlActionReceipt
typealias NativeMacActionCommandRunning = MacControlCommandRunning
typealias NativeMacActionProcessRunner = MacControlProcessRunner
typealias NativeMacActionBroker = MacControlActionBroker
typealias NativeMacActionPolicy = MacControlPolicy
