import ClawHostKit
import Foundation

typealias NativeMacActionWireActor = MacControlWireActor
typealias NativeMacActionWireHost = MacControlWireHost
typealias NativeMacActionWireTarget = MacControlWireTarget
typealias NativeMacActionWireRequest = MacControlWireRequest
typealias NativeMacActionWirePermissionRequirement = MacControlWirePermissionRequirement
typealias NativeMacActionWireRequiredApproval = MacControlWireRequiredApproval
typealias NativeMacActionWireRollbackPlan = MacControlWireRollbackPlan
typealias NativeMacActionWirePlan = MacControlWirePlan
typealias NativeMacActionWireRedaction = MacControlWireRedaction
typealias NativeMacActionWireReceipt = MacControlWireReceipt
typealias NativeMacActionWireAuditEvent = MacControlWireAuditEvent
typealias NativeMacActionWireEvaluation = MacControlWireEvaluation
typealias NativeMacActionWire = MacControlWire
