import type { PomodoroCategory, PomodoroSettings } from "./pomodoro-model";

export function defaultPomodoroCategories(): PomodoroCategory[] {
  return [
    { id: "general", name: "General", color: "#ef5b5b" },
    { id: "deep-work", name: "Deep work", color: "#73a6ff" },
    { id: "admin", name: "Admin", color: "#f1b85b" },
  ];
}

export function defaultPomodoroSettings(): PomodoroSettings {
  return {
    dailyGoalMinutes: 120,
    showSuggestionsBy: "all",
    focusIntentionOnCategoryChange: true,
    autoStartSuggestion: true,
    snapIntervalMinutes: 5,
    autoStartFocus: false,
    autoStartBreak: false,
    defaultMood: "neutral",
    askReflection: false,
    sleepAction: "nothing",
    launchAtLogin: false,
    sessionMinutes: 25,
    shortBreakMinutes: 5,
    longBreakMinutes: 20,
    longBreakAfterFocusMinutes: 90,
    breathCount: 1,
    sessionMainAction: "restart",
    breakMainAction: "start-session",
    endingSoonEnabled: true,
    endingSoonMinutes: 2,
    endingSoonSound: true,
    presenceEnabled: false,
    sessionOverflowEnabled: true,
    pauseOverflowEnabled: true,
    breakOverflowEnabled: true,
    overflowMinutes: 10,
    backgroundSoundEnabled: false,
    sessionSound: "Clock Ticking",
    sessionEndSound: "Kitchen Timer",
    breakSound: "Ocean Waves",
    breakEndSound: "Gong",
    sessionVolume: 0.05,
    sessionEndVolume: 0.5,
    breakVolume: 0.5,
    breakEndVolume: 0.5,
    sessionWebBlocker: { enabled: false, type: "deny", entries: "" },
    breakWebBlocker: { enabled: false, type: "deny", entries: "" },
    sessionAppBlocker: { enabled: false, apps: [] },
    breakAppBlocker: { enabled: false, apps: [] },
    slackBlockerEnabled: false,
    slackTeams: [],
    menuShowDuration: true,
    menuShowCategory: true,
    menuShowTodayTotal: false,
    showDockIcon: true,
    keepWindowOnTop: false,
    keepWindowOnTopOnBreak: true,
    showOnAllSpaces: false,
    minimizeWhenStarted: false,
    showOnTimerEnd: true,
    windowTrackerEnabled: false,
    windowTrackers: [],
    theme: "system",
    language: "en",
    localShortcutsEnabled: true,
    globalShortcutsEnabled: false,
    appleScriptEnabled: true,
    urlSchemeEnabled: true,
    developerTodoPreview: true,
  };
}
