import Foundation
import Combine
import ClawixCore
import ClawixEngine

@main
struct BridgedMain {
    static func main() {
        BridgedLog.write("starting schemaVersion=\(bridgeSchemaVersion)")
        let env = ProcessInfo.processInfo.environment
        if let bearer = env["CLAWIX_BRIDGED_BEARER"], !bearer.isEmpty {
            UserDefaults.standard.set(bearer, forKey: "ClawixBridge.Bearer.v1")
        }

        let port = env["CLAWIX_BRIDGED_PORT"].flatMap(UInt16.init) ?? 7778
        let defaults = env["CLAWIX_BRIDGED_DEFAULTS_SUITE"]
            .flatMap { UserDefaults(suiteName: $0) }
            ?? .standard
        let pairing = PairingService(defaults: defaults, port: port)
        // Force the bearer + short code to materialize at startup so
        // external surfaces (the npm CLI's `clawix pair`, the menubar
        // helper, a future iOS app reading the suite directly) can pull
        // the QR payload without first opening a websocket. Both are
        // lazily generated by their getters; touching them once writes
        // to UserDefaults if not already there.
        _ = pairing.bearer
        _ = pairing.shortCode
        let publishBonjour = env["CLAWIX_BRIDGED_DISABLE_BONJOUR"] != "1"
        let box = HostBox()
        BridgedHeartbeat.start(port: port)

        Task { @MainActor in
            guard let binary = BackendBinary.resolve(environment: env) else {
                BridgedLog.write("backend binary not found")
                exit(78)
            }
            let host = DaemonEngineHost(binary: binary, pairing: pairing)
            let server = BridgeServer(
                host: host,
                port: port,
                pairing: pairing,
                publishBonjour: publishBonjour
            )
            server.start()
            box.host = host
            box.server = server
            BridgedLog.write("listening tcp/\(port) backend=\(binary.path.path)")
            Task { @MainActor in
                await host.bootstrap()
            }
        }

        RunLoop.current.run()
    }
}

final class HostBox: @unchecked Sendable {
    var host: AnyObject?
    var server: AnyObject?
}

/// Periodic heartbeat to a tiny JSON file under
/// `~/.clawix/state/bridge-status.json`. The npm CLI reads this file
/// to drive `clawix status` and the live watch in `clawix up` without
/// opening an authenticated websocket. Atomic write (`.tmp` + rename)
/// so a reader never sees a half-flushed JSON. peerCount stays 0 in
/// this iteration; wiring it to `BridgeServer` lives in v1.x.
enum BridgedHeartbeat {
    private static let interval: TimeInterval = 2.0

    static func start(port: UInt16) {
        let queue = DispatchQueue(label: "com.clawix.bridge.heartbeat", qos: .utility)
        let timer = DispatchSource.makeTimerSource(queue: queue)
        timer.schedule(deadline: .now(), repeating: interval, leeway: .milliseconds(200))
        let boundAt = Self.iso8601(Date())
        let pid = Int(getpid())
        timer.setEventHandler {
            write(pid: pid, port: port, boundAt: boundAt)
        }
        timer.resume()
        // Keep a strong reference so the source is not deallocated.
        TimerBox.shared.timer = timer
    }

    private static func write(pid: Int, port: UInt16, boundAt: String) {
        let stateDir = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".clawix/state", isDirectory: true)
        try? FileManager.default.createDirectory(at: stateDir, withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700])
        let target = stateDir.appendingPathComponent("bridge-status.json")
        let tmp = stateDir.appendingPathComponent("bridge-status.json.tmp")

        let payload: [String: Any] = [
            "version": "0.1.1",
            "pid": pid,
            "port": Int(port),
            "boundAt": boundAt,
            "lastHeartbeatAt": iso8601(Date()),
            "peerCount": BridgeStats.shared.activeSessionCount,
            "lastError": NSNull()
        ]
        guard let data = try? JSONSerialization.data(withJSONObject: payload, options: [.sortedKeys, .prettyPrinted]) else { return }
        do {
            try data.write(to: tmp, options: .atomic)
            try? FileManager.default.removeItem(at: target)
            try FileManager.default.moveItem(at: tmp, to: target)
        } catch {
            BridgedLog.write("heartbeat write failed: \(error)")
        }
    }

    private static let isoFormatter: ISO8601DateFormatter = {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return f
    }()

    private static func iso8601(_ date: Date) -> String { isoFormatter.string(from: date) }
}

final class TimerBox: @unchecked Sendable {
    static let shared = TimerBox()
    var timer: DispatchSourceTimer?
}

enum BridgedLog {
    static func write(_ message: String) {
        let safe = redact(message)
        FileHandle.standardError.write(Data(("[clawix-bridged] \(safe)\n").utf8))
    }

    private static func redact(_ s: String) -> String {
        let patterns = [
            "(?<![A-Za-z0-9_-])[A-Za-z0-9_-]{32,}(?![A-Za-z0-9_-])",
            NSHomeDirectory().replacingOccurrences(of: "/", with: "\\/")
        ]
        return patterns.reduce(s) { current, pattern in
            guard let re = try? NSRegularExpression(pattern: pattern) else { return current }
            let range = NSRange(current.startIndex..., in: current)
            let replacement = pattern.hasPrefix("(?<!") ? "<redacted>" : "~"
            return re.stringByReplacingMatches(in: current, range: range, withTemplate: replacement)
        }
    }
}

struct BackendBinary {
    let path: URL

    static func resolve(environment: [String: String]) -> BackendBinary? {
        if let override = environment["CLAWIX_BRIDGED_BACKEND_PATH"], !override.isEmpty {
            let url = URL(fileURLWithPath: (override as NSString).expandingTildeInPath)
            if FileManager.default.isExecutableFile(atPath: url.path) {
                return BackendBinary(path: url)
            }
        }
        for candidate in candidatePaths() where FileManager.default.isExecutableFile(atPath: candidate.path) {
            return BackendBinary(path: candidate)
        }
        return nil
    }

    private static func candidatePaths() -> [URL] {
        var out: [URL] = []
        if let manual = UserDefaults.standard.string(forKey: "ClawixBinaryPath"), !manual.isEmpty {
            out.append(URL(fileURLWithPath: manual))
        }
        out.append(URL(fileURLWithPath: "/Applications/Codex.app/Contents/Resources/codex"))
        let nvmRoot = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".nvm/versions/node", isDirectory: true)
        if let versions = try? FileManager.default.contentsOfDirectory(at: nvmRoot, includingPropertiesForKeys: nil) {
            for version in versions.sorted(by: { $0.lastPathComponent > $1.lastPathComponent }) {
                out.append(version.appendingPathComponent("bin/codex"))
            }
        }
        out.append(URL(fileURLWithPath: "/opt/homebrew/bin/codex"))
        out.append(URL(fileURLWithPath: "/usr/local/bin/codex"))
        out.append(URL(fileURLWithPath: "/usr/bin/codex"))
        return out
    }
}

@MainActor
final class DaemonEngineHost: EngineHost {
    private let backend: BackendClient
    private let pairing: PairingService
    private let chatsSubject = CurrentValueSubject<[BridgeChatSnapshot], Never>([])
    private var chatByThread: [String: String] = [:]
    private var threadByChat: [String: String] = [:]
    private var rolloutPathByThread: [String: String] = [:]
    private var activeAssistantIdByThread: [String: String] = [:]
    private var activeTurnByThread: [String: String] = [:]

    init(binary: BackendBinary, pairing: PairingService) {
        self.backend = BackendClient(binary: binary)
        self.pairing = pairing
    }

    var bridgeChatsCurrent: [BridgeChatSnapshot] { chatsSubject.value }
    var bridgeChatsPublisher: AnyPublisher<[BridgeChatSnapshot], Never> {
        chatsSubject.eraseToAnyPublisher()
    }

    func bootstrap() async {
        do {
            try await backend.start()
            startEvents()
            _ = try await backend.send(
                method: "initialize",
                params: InitializeParams(
                    clientInfo: InitializeClientInfo(name: "Clawix Bridged", title: "Clawix", version: "1"),
                    capabilities: InitializeCapabilities(experimentalApi: true, optOutNotificationMethods: nil)
                )
            )
            try await backend.notify(method: "initialized", params: EmptyObject())
            await reloadThreads()
        } catch {
            BridgedLog.write("bootstrap failed \(error)")
        }
    }

    func handleHydrateHistory(chatId: UUID) {
        hydrate(chatId: chatId.uuidString)
    }

    func handleSendPrompt(chatId: UUID, text: String, attachments: [WireAttachment]) {
        let chatIdString = chatId.uuidString
        // Split image vs audio attachments. Images go to Codex as
        // `localImage` items; audio is transcribed via Whisper, stored
        // for future replay, and the transcript becomes (or augments)
        // the prompt text the model sees. Order is preserved within
        // each kind, which is enough since the iPhone composer never
        // mixes images with audio in the same send today.
        let imageAttachments = attachments.filter { $0.kind == .image }
        let audioAttachments = attachments.filter { $0.kind == .audio }
        Task { @MainActor in
            do {
                let threadId = try await ensureThread(chatId: chatIdString, firstPrompt: text)
                let imagePaths = AttachmentSpooler.write(
                    attachments: imageAttachments,
                    scope: threadId,
                    log: { BridgedLog.write($0) }
                )
                // Transcribe + persist each audio attachment in order.
                // The user message ID is minted up-front so the audio
                // store entry can carry it (helps the GUI's own
                // hydrate path attach the bubble back without having
                // to re-match by content).
                let userMessageId = UUID().uuidString
                let audioRef = try await ingestAudioAttachments(
                    audioAttachments,
                    threadId: threadId,
                    chatId: chatIdString,
                    messageId: userMessageId,
                    providedTranscript: text
                )
                // Audio's transcript replaces the text input when the
                // user sent only a voice clip (the iPhone composer
                // sends `text == transcript` already, but defending
                // against an empty `text` field is cheap and lets the
                // shape stay simple for future surfaces that ship an
                // audio-only prompt).
                let promptText: String = {
                    if !text.isEmpty { return text }
                    if let audioRef, !audioRef.transcript.isEmpty { return audioRef.transcript }
                    return text
                }()
                let preview = userMessagePreview(
                    text: promptText,
                    imageCount: imagePaths.count,
                    hasAudio: audioRef != nil
                )
                appendMessage(chatId: chatIdString, message: WireMessage(
                    id: userMessageId,
                    role: .user,
                    content: preview,
                    streamingFinished: true,
                    timestamp: Date(),
                    audioRef: audioRef?.wireRef
                ))
                updateChat(chatId: chatIdString) { chat in
                    chat.hasActiveTurn = true
                    chat.lastTurnInterrupted = false
                    chat.lastMessageAt = Date()
                    chat.lastMessagePreview = String(preview.prefix(140))
                }
                var input: [TurnStartUserInput] = []
                if !promptText.isEmpty { input.append(.text(promptText)) }
                for path in imagePaths { input.append(.localImage(path: path)) }
                if input.isEmpty { input.append(.text(promptText)) }
                let result = try await backend.send(
                    method: "turn/start",
                    params: TurnStartParams(
                        threadId: threadId,
                        input: input,
                        model: nil,
                        effort: nil,
                        serviceTier: nil,
                        collaborationMode: nil
                    ),
                    expecting: TurnStartResult.self
                )
                activeTurnByThread[threadId] = result.turn.id
            } catch {
                appendError(chatId: chatIdString, message: "\(error)")
            }
        }
    }

    /// Whisper-transcribe each audio attachment, persist the bytes via
    /// `AudioMessageStore`, and return a wire-ready ref pointing at the
    /// most recent (or only) clip. Today the iPhone composer ships at
    /// most one audio per send; the loop is defensive in case a future
    /// surface chains multiple takes. Order is preserved by the caller
    /// reading the array in order, so the last entry wins as the
    /// canonical audioRef on the user message.
    private func ingestAudioAttachments(
        _ attachments: [WireAttachment],
        threadId: String,
        chatId: String,
        messageId: String,
        providedTranscript: String
    ) async throws -> AudioStoreEntry? {
        guard !attachments.isEmpty else { return nil }
        // The iPhone composer transcribes locally (via the existing
        // `transcribeAudio` frame) before sending so the user sees the
        // bubble go up at the speed of network, not the speed of
        // Whisper. We honour that transcript: if the client already
        // provided one, the daemon stores it without re-running the
        // model. Only when the client shipped audio without text (a
        // future "raw audio prompt" surface) does the daemon fall back
        // to its own Whisper run so the audio store sidecar still
        // carries something useful for the hydrate-decoration path.
        let normalizedTranscript = providedTranscript.trimmingCharacters(in: .whitespacesAndNewlines)
        var fallbackTranscript: String? = nil
        if normalizedTranscript.isEmpty {
            let suiteName = ProcessInfo.processInfo.environment["CLAWIX_BRIDGED_DEFAULTS_SUITE"]
            let defaults = suiteName.flatMap { UserDefaults(suiteName: $0) } ?? .standard
            let activeRaw = defaults.string(forKey: DictationModelManager.activeModelDefaultsKey) ?? ""
            let model = DictationModel(rawValue: activeRaw) ?? .default
            // Only run Whisper for the first attachment; multi-clip
            // turns aren't a thing today and concatenating partial
            // transcripts across clips would lose ordering anyway.
            if let first = attachments.first, let data = Data(base64Encoded: first.dataBase64) {
                let tmpDir = URL(fileURLWithPath: NSTemporaryDirectory())
                    .appendingPathComponent("clawix-attachments", isDirectory: true)
                    .appendingPathComponent("ingest", isDirectory: true)
                try? FileManager.default.createDirectory(at: tmpDir, withIntermediateDirectories: true)
                let ext = AudioMessageStore.fileExtension(for: first.mimeType)
                let tmpURL = tmpDir.appendingPathComponent("\(first.id).\(ext)")
                try? data.write(to: tmpURL, options: .atomic)
                if let transcript = try? await TranscriptionService.shared.transcribe(
                    fileURL: tmpURL,
                    using: model,
                    language: nil
                ) {
                    fallbackTranscript = transcript
                }
                try? FileManager.default.removeItem(at: tmpURL)
            }
        }

        var lastEntry: AudioStoreEntry?
        for attachment in attachments {
            guard let data = Data(base64Encoded: attachment.dataBase64) else {
                BridgedLog.write("audio attachment decode failed id=\(attachment.id)")
                continue
            }
            let entry = try await AudioMessageStore.shared.ingest(
                threadId: threadId,
                chatId: chatId,
                messageId: messageId,
                audioData: data,
                mimeType: attachment.mimeType,
                transcript: normalizedTranscript.isEmpty ? (fallbackTranscript ?? "") : normalizedTranscript
            )
            lastEntry = entry
        }
        return lastEntry
    }

    private func userMessagePreview(text: String, imageCount: Int, hasAudio: Bool = false) -> String {
        // The chat row preview shows the same text Codex actually
        // received as the prompt; if there are images the count gets
        // inlined the way the macOS composer already does. Audio
        // messages don't add a tag because the transcript already is
        // the visible content and surfaces (chat row, timeline) read
        // cleaner without a "[voice]" prefix muddying user prompts.
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard imageCount > 0 else {
            return hasAudio && trimmed.isEmpty ? "[voice]" : text
        }
        let label = imageCount == 1 ? "[image]" : "[\(imageCount) images]"
        return trimmed.isEmpty ? label : "\(label) \(text)"
    }

    func handleNewChat(chatId: UUID, text: String, attachments: [WireAttachment]) {
        // The iPhone composer treats the first prompt of a chat as a
        // `newChat` frame so the daemon can mint the thread with the
        // chat's pre-allocated UUID. The actual run path is identical
        // to a regular send: ensureThread creates the thread on demand.
        handleSendPrompt(chatId: chatId, text: text, attachments: attachments)
    }

    func handleRequestAudio(
        audioId: String,
        reply: @MainActor @escaping (String?, String?, String?) -> Void
    ) {
        // The bridge thread posts this; jump back to MainActor for the
        // reply send so the session.send path stays single-actor like
        // the other handlers.
        Task { @MainActor in
            if let payload = await AudioMessageStore.shared.data(forAudioId: audioId) {
                reply(payload.data.base64EncodedString(), payload.mimeType, nil)
            } else {
                reply(nil, nil, "Audio no longer available")
            }
        }
    }

    func handleTranscribeAudio(
        requestId: String,
        audioBase64: String,
        mimeType: String,
        language: String?,
        reply: @MainActor @escaping (String, String?) -> Void
    ) {
        // Audio blobs from the iPhone arrive base64-encoded inside the
        // bridge frame because the WebSocket transport is text-only.
        // Spool to a per-request file in the same /tmp tree the image
        // attachment path uses, then hand the file to WhisperKit.
        let suiteName = ProcessInfo.processInfo.environment["CLAWIX_BRIDGED_DEFAULTS_SUITE"]
        let defaults = suiteName.flatMap { UserDefaults(suiteName: $0) } ?? .standard
        let activeRaw = defaults.string(forKey: DictationModelManager.activeModelDefaultsKey) ?? ""
        let model = DictationModel(rawValue: activeRaw) ?? .default

        Task { @MainActor in
            let ext = audioExtension(mimeType: mimeType)
            let root = URL(fileURLWithPath: NSTemporaryDirectory())
                .appendingPathComponent("clawix-attachments", isDirectory: true)
                .appendingPathComponent("dictation", isDirectory: true)
            let url = root.appendingPathComponent("\(requestId).\(ext)")
            do {
                try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
                guard let data = Data(base64Encoded: audioBase64) else {
                    reply("", "Audio decode failed")
                    return
                }
                try data.write(to: url, options: .atomic)
                let text = try await TranscriptionService.shared.transcribe(
                    fileURL: url,
                    using: model,
                    language: language
                )
                reply(text, nil)
            } catch {
                reply("", error.localizedDescription)
            }
        }
    }

    func handleInterruptTurn(chatId: UUID) {
        let chatIdString = chatId.uuidString
        guard let threadId = threadByChat[chatIdString],
              let turnId = activeTurnByThread[threadId]
        else { return }
        // Clear UI-side state first so the iPhone shimmer disappears the
        // moment the frame round-trips back. The backend cancel is
        // fire-and-forget; any deltas already in flight for this turn
        // are gated by `activeTurnByThread`/`activeAssistantIdByThread`.
        activeTurnByThread[threadId] = nil
        if let assistantId = activeAssistantIdByThread[threadId] {
            // Mirror the macOS behaviour: if the assistant placeholder
            // is still empty (no streamed content), drop it; otherwise
            // freeze it as finished so the partial answer stays.
            let messages = existingMessages(chatId: chatIdString)
            if let msg = messages.first(where: { $0.id == assistantId }),
               msg.content.isEmpty && msg.reasoningText.isEmpty {
                updateSnapshot(chatId: chatIdString) { snap in
                    snap.messages.removeAll { $0.id == assistantId }
                }
            } else {
                updateMessage(chatId: chatIdString, messageId: assistantId) {
                    $0.streamingFinished = true
                }
            }
            activeAssistantIdByThread[threadId] = nil
        }
        updateChat(chatId: chatIdString) {
            $0.hasActiveTurn = false
            $0.lastTurnInterrupted = true
        }
        Task { @MainActor in
            do {
                _ = try await backend.send(
                    method: "turn/interrupt",
                    params: TurnInterruptParams(threadId: threadId, turnId: turnId),
                    expecting: EmptyResponse.self
                )
            } catch {
                BridgedLog.write("turn/interrupt failed \(error)")
            }
        }
    }

    func handleArchiveChat(chatId: UUID, archived: Bool) {
        let chatIdString = chatId.uuidString
        guard let threadId = threadByChat[chatIdString] else { return }
        Task { @MainActor in
            do {
                if archived {
                    _ = try await backend.send(
                        method: "thread/archive",
                        params: ThreadArchiveParams(threadId: threadId),
                        expecting: EmptyResponse.self
                    )
                } else {
                    _ = try await backend.send(
                        method: "thread/unarchive",
                        params: ThreadUnarchiveParams(threadId: threadId),
                        expecting: EmptyResponse.self
                    )
                }
                updateChat(chatId: chatIdString) {
                    $0.isArchived = archived
                    if archived { $0.isPinned = false }
                }
            } catch {
                appendError(chatId: chatIdString, message: "\(error)")
            }
        }
    }

    func handleRenameChat(chatId: UUID, title: String) {
        let trimmed = title.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        let chatIdString = chatId.uuidString
        guard let threadId = threadByChat[chatIdString] else { return }
        // Optimistic local update so any client subscribed to this
        // session sees the new title before the runtime ack lands. The
        // bus will republish via `chatUpdated`, which all peers (the
        // initiating iPhone included) treat as the canonical state.
        updateChat(chatId: chatIdString) {
            $0.title = trimmed
        }
        Task { @MainActor in
            do {
                _ = try await backend.send(
                    method: "thread/name/set",
                    params: ThreadSetNameParams(threadId: threadId, name: trimmed),
                    expecting: EmptyResponse.self
                )
            } catch {
                appendError(chatId: chatIdString, message: "\(error)")
            }
        }
    }

    func handlePairingStart() -> (qrJson: String, bearer: String)? {
        return (pairing.qrPayload(), pairing.bearer)
    }

    private func reloadThreads() async {
        do {
            let response = try await backend.send(
                method: "thread/list",
                params: ThreadListParams(
                    archived: false,
                    cursor: nil,
                    cwd: nil,
                    limit: 160,
                    modelProviders: nil,
                    searchTerm: nil,
                    sortDirection: "desc",
                    sortKey: "updated_at",
                    sourceKinds: nil,
                    useStateDbOnly: true
                ),
                expecting: ThreadListResponse.self
            )
            let snapshots = response.data.map(snapshot(from:))
            chatsSubject.send(snapshots)
        } catch {
            BridgedLog.write("thread/list failed \(error)")
        }
    }

    private func snapshot(from thread: AgentThreadSummary) -> BridgeChatSnapshot {
        let chatId = chatByThread[thread.id] ?? UUID().uuidString
        chatByThread[thread.id] = chatId
        threadByChat[chatId] = thread.id
        if let path = thread.path { rolloutPathByThread[thread.id] = path }
        return BridgeChatSnapshot(
            chat: WireChat(
                id: chatId,
                title: title(for: thread),
                createdAt: thread.updatedDate,
                isArchived: thread.archived ?? false,
                hasActiveTurn: activeTurnByThread[thread.id] != nil,
                lastMessageAt: thread.updatedDate,
                lastMessagePreview: thread.preview,
                cwd: thread.cwd
            ),
            messages: existingMessages(chatId: chatId)
        )
    }

    private func title(for thread: AgentThreadSummary) -> String {
        if let name = thread.name?.trimmingCharacters(in: .whitespacesAndNewlines), !name.isEmpty {
            return name
        }
        let preview = thread.preview.trimmingCharacters(in: .whitespacesAndNewlines)
        return preview.isEmpty ? "Conversation" : String(preview.prefix(60))
    }

    private func ensureThread(chatId: String, firstPrompt: String) async throws -> String {
        if let threadId = threadByChat[chatId] {
            return threadId
        }
        let result = try await backend.send(
            method: "thread/start",
            params: ThreadStartParams(
                cwd: FileManager.default.homeDirectoryForCurrentUser.path,
                model: nil,
                approvalPolicy: nil,
                sandbox: nil,
                personality: nil,
                serviceTier: nil,
                collaborationMode: nil
            ),
            expecting: ThreadStartResult.self
        )
        let threadId = result.thread.id
        chatByThread[threadId] = chatId
        threadByChat[chatId] = threadId
        ensureSnapshot(chatId: chatId, firstPrompt: firstPrompt, cwd: result.thread.cwd)
        updateSnapshot(chatId: chatId) { snap in
            let trimmed = firstPrompt.trimmingCharacters(in: .whitespacesAndNewlines)
            snap.chat.title = trimmed.isEmpty ? "Conversation" : String(trimmed.prefix(60))
            snap.chat.cwd = result.thread.cwd
        }
        return threadId
    }

    private func ensureSnapshot(chatId: String, firstPrompt: String, cwd: String?) {
        guard !bridgeChatsCurrent.contains(where: { $0.id == chatId }) else { return }
        let trimmed = firstPrompt.trimmingCharacters(in: .whitespacesAndNewlines)
        var snapshots = bridgeChatsCurrent
        snapshots.insert(
            BridgeChatSnapshot(
                chat: WireChat(
                    id: chatId,
                    title: trimmed.isEmpty ? "Conversation" : String(trimmed.prefix(60)),
                    createdAt: Date(),
                    isArchived: false,
                    hasActiveTurn: false,
                    lastMessageAt: Date(),
                    lastMessagePreview: String(trimmed.prefix(140)),
                    cwd: cwd
                ),
                messages: []
            ),
            at: 0
        )
        chatsSubject.send(snapshots)
    }

    private func hydrate(chatId: String) {
        guard let threadId = threadByChat[chatId],
              let path = rolloutPathByThread[threadId]
        else { return }
        let result = RolloutHistory.read(path: URL(fileURLWithPath: path))
        guard !result.messages.isEmpty || result.lastTurnInterrupted else { return }
        // Audio refs from previous sessions live in the AudioMessageStore.
        // Rollout rebuild mints fresh message ids so we can't key by id;
        // instead we walk audio entries (chronological) and pair them up
        // with rebuilt user_messages, prefering content-equality and
        // breaking ties by ordinal. Missing entries decay gracefully:
        // the user message just shows without a bubble, the bytes are
        // still on disk and `requestAudio` still works if a client knows
        // the audioId from another route.
        Task { @MainActor in
            let audioEntries = await AudioMessageStore.shared.entries(forThread: threadId)
            var decorated = result.messages
            if !audioEntries.isEmpty {
                var unmatched = audioEntries
                for idx in decorated.indices where decorated[idx].role == .user {
                    let content = decorated[idx].content
                    let pickIdx: Int? = {
                        if let exact = unmatched.firstIndex(where: { $0.transcript == content }) {
                            return exact
                        }
                        return unmatched.indices.first
                    }()
                    if let pickIdx {
                        decorated[idx].audioRef = unmatched[pickIdx].wireRef
                        unmatched.remove(at: pickIdx)
                    }
                }
            }
            self.updateSnapshot(chatId: chatId) { snap in
                snap.messages = decorated
                snap.chat.lastTurnInterrupted = result.lastTurnInterrupted
                if let last = decorated.last {
                    snap.chat.lastMessageAt = last.timestamp
                    snap.chat.lastMessagePreview = String(last.content.prefix(140))
                }
            }
        }
    }

    private func startEvents() {
        let stream = backend.events
        Task { @MainActor in
            for await event in stream {
                handle(event)
            }
        }
    }

    private func handle(_ event: BackendEvent) {
        switch event {
        case let .request(id, method, _):
            if method == "item/tool/requestUserInput" {
                try? backend.resolve(id: id, result: ToolRequestUserInputResponse(answers: [:]))
            }
        case let .notification(method, params):
            handleNotification(method: method, params: params)
        }
    }

    private func handleNotification(method: String, params: JSONValue?) {
        switch method {
        case "turn/started":
            guard let payload = try? params?.decode(TurnEnvelope.self),
                  let chatId = chatByThread[payload.threadId]
            else { return }
            activeTurnByThread[payload.threadId] = payload.turn.id
            ensureAssistant(chatId: chatId, threadId: payload.threadId)
            updateChat(chatId: chatId) { $0.hasActiveTurn = true }
        case "item/agentMessage/delta":
            guard let payload = try? params?.decode(AgentMessageDelta.self),
                  let chatId = chatByThread[payload.threadId]
            else { return }
            let assistantId = ensureAssistant(chatId: chatId, threadId: payload.threadId)
            updateMessage(chatId: chatId, messageId: assistantId) { msg in
                msg.content += payload.delta
                msg.streamingFinished = false
            }
        case "item/reasoning/textDelta", "item/reasoning/summaryTextDelta":
            guard let payload = try? params?.decode(ReasoningTextDelta.self),
                  let chatId = chatByThread[payload.threadId]
            else { return }
            let assistantId = ensureAssistant(chatId: chatId, threadId: payload.threadId)
            updateMessage(chatId: chatId, messageId: assistantId) { msg in
                msg.reasoningText += payload.delta
                msg.streamingFinished = false
            }
        case "item/completed":
            guard let payload = try? params?.decode(ItemEnvelope.self),
                  payload.item.type == "agentMessage",
                  let chatId = chatByThread[payload.threadId],
                  let assistantId = activeAssistantIdByThread[payload.threadId]
            else { return }
            updateMessage(chatId: chatId, messageId: assistantId) { msg in
                if let text = payload.item.text, !text.isEmpty {
                    msg.content = text
                }
                msg.streamingFinished = true
            }
        case "turn/completed":
            guard let payload = try? params?.decode(TurnEnvelope.self),
                  let chatId = chatByThread[payload.threadId]
            else { return }
            activeTurnByThread[payload.threadId] = nil
            activeAssistantIdByThread[payload.threadId] = nil
            updateChat(chatId: chatId) {
                $0.hasActiveTurn = false
                $0.lastTurnInterrupted = false
            }
        default:
            break
        }
    }

    @discardableResult
    private func ensureAssistant(chatId: String, threadId: String) -> String {
        if let id = activeAssistantIdByThread[threadId] { return id }
        let id = UUID().uuidString
        activeAssistantIdByThread[threadId] = id
        appendMessage(chatId: chatId, message: WireMessage(
            id: id,
            role: .assistant,
            content: "",
            streamingFinished: false,
            timestamp: Date()
        ))
        return id
    }

    private func appendError(chatId: String, message: String) {
        appendMessage(chatId: chatId, message: WireMessage(
            id: UUID().uuidString,
            role: .assistant,
            content: message,
            streamingFinished: true,
            isError: true,
            timestamp: Date()
        ))
        updateChat(chatId: chatId) { $0.hasActiveTurn = false }
    }

    private func existingMessages(chatId: String) -> [WireMessage] {
        bridgeChatsCurrent.first(where: { $0.id == chatId })?.messages ?? []
    }

    private func appendMessage(chatId: String, message: WireMessage) {
        updateSnapshot(chatId: chatId) { snap in
            snap.messages.append(message)
            snap.chat.lastMessageAt = message.timestamp
            snap.chat.lastMessagePreview = String(message.content.prefix(140))
        }
    }

    private func updateMessage(chatId: String, messageId: String, mutate: (inout WireMessage) -> Void) {
        updateSnapshot(chatId: chatId) { snap in
            guard let idx = snap.messages.firstIndex(where: { $0.id == messageId }) else { return }
            mutate(&snap.messages[idx])
            let msg = snap.messages[idx]
            snap.chat.lastMessageAt = msg.timestamp
            snap.chat.lastMessagePreview = String(msg.content.prefix(140))
        }
    }

    private func updateChat(chatId: String, mutate: (inout WireChat) -> Void) {
        updateSnapshot(chatId: chatId) { mutate(&$0.chat) }
    }

    private func updateSnapshot(chatId: String, mutate: (inout MutableSnapshot) -> Void) {
        var snapshots = bridgeChatsCurrent
        guard let index = snapshots.firstIndex(where: { $0.id == chatId }) else { return }
        var mutable = MutableSnapshot(snapshots[index])
        mutate(&mutable)
        snapshots[index] = mutable.snapshot
        chatsSubject.send(snapshots)
    }
}

private struct MutableSnapshot {
    var chat: WireChat
    var messages: [WireMessage]

    init(_ snapshot: BridgeChatSnapshot) {
        self.chat = snapshot.chat
        self.messages = snapshot.messages
    }

    var snapshot: BridgeChatSnapshot {
        BridgeChatSnapshot(chat: chat, messages: messages)
    }
}

actor BackendClient {
    private let binary: BackendBinary
    private var process: Process?
    private var stdin: Pipe?
    private var stdoutBuffer = Data()
    private var nextId = 1
    private var pending: [Int: CheckedContinuation<JSONValue?, Error>] = [:]
    private let continuationBox = EventContinuationBox()
    nonisolated let events: AsyncStream<BackendEvent>

    init(binary: BackendBinary) {
        self.binary = binary
        var captured: AsyncStream<BackendEvent>.Continuation?
        self.events = AsyncStream { continuation in
            captured = continuation
        }
        continuationBox.continuation = captured
    }

    func start() throws {
        guard process == nil else { return }
        let proc = Process()
        proc.executableURL = binary.path
        proc.arguments = ["app-server", "--listen", "stdio://"]
        var env = ProcessInfo.processInfo.environment
        env["CODEX_HOME"] = nil
        proc.environment = env
        let input = Pipe()
        let output = Pipe()
        let error = Pipe()
        proc.standardInput = input
        proc.standardOutput = output
        proc.standardError = error
        stdin = input
        attachStdout(output)
        attachStderr(error)
        try proc.run()
        process = proc
        proc.terminationHandler = { [weak self] _ in
            Task { await self?.handleTermination() }
        }
    }

    func send<P: Encodable>(method: String, params: P) async throws -> JSONValue? {
        guard process != nil else { throw BackendError.notRunning }
        let id = nextId
        nextId += 1
        return try await withCheckedThrowingContinuation { continuation in
            pending[id] = continuation
            do {
                try write(BackendRequest(id: id, method: method, params: params))
            } catch {
                pending.removeValue(forKey: id)
                continuation.resume(throwing: error)
            }
        }
    }

    func send<P: Encodable, R: Decodable>(method: String, params: P, expecting: R.Type) async throws -> R {
        guard let raw = try await send(method: method, params: params) else {
            throw BackendError.invalidResponse
        }
        return try raw.decode(R.self)
    }

    func notify<P: Encodable>(method: String, params: P) throws {
        try write(BackendNotification(method: method, params: params))
    }

    nonisolated func resolve<R: Encodable>(id: RPCID, result: R) throws {
        Task { try await self.write(BackendResponse(id: id, result: result)) }
    }

    private func attachStdout(_ pipe: Pipe) {
        let weak = WeakBackend(self)
        pipe.fileHandleForReading.readabilityHandler = { handle in
            let data = handle.availableData
            if data.isEmpty {
                handle.readabilityHandler = nil
                return
            }
            Task { await weak.value?.appendStdout(data) }
        }
    }

    private func attachStderr(_ pipe: Pipe) {
        pipe.fileHandleForReading.readabilityHandler = { handle in
            let data = handle.availableData
            if data.isEmpty {
                handle.readabilityHandler = nil
                return
            }
            if let text = String(data: data, encoding: .utf8), !text.isEmpty {
                BridgedLog.write("backend stderr \(text.trimmingCharacters(in: .whitespacesAndNewlines))")
            }
        }
    }

    private func appendStdout(_ data: Data) {
        stdoutBuffer.append(data)
        while let nl = stdoutBuffer.firstIndex(of: 0x0a) {
            let line = stdoutBuffer.subdata(in: 0..<nl)
            stdoutBuffer.removeSubrange(0...nl)
            guard !line.isEmpty else { continue }
            handleLine(line)
        }
    }

    private func handleLine(_ data: Data) {
        guard let message = try? JSONDecoder().decode(BackendIncoming.self, from: data) else { return }
        if let id = message.id, message.method == nil {
            guard case .int(let intId) = id, let continuation = pending.removeValue(forKey: intId) else { return }
            if let error = message.error {
                continuation.resume(throwing: BackendError.rpc(error.message))
            } else {
                continuation.resume(returning: message.result)
            }
            return
        }
        if let method = message.method {
            if let id = message.id {
                continuationBox.continuation?.yield(.request(id: id, method: method, params: message.params))
            } else {
                continuationBox.continuation?.yield(.notification(method: method, params: message.params))
            }
        }
    }

    private func write<T: Encodable>(_ value: T) throws {
        guard let stdin else { throw BackendError.notRunning }
        let data = try JSONEncoder().encode(value) + Data([0x0a])
        try stdin.fileHandleForWriting.write(contentsOf: data)
    }

    private func handleTermination() {
        process = nil
        for continuation in pending.values {
            continuation.resume(throwing: BackendError.notRunning)
        }
        pending.removeAll()
    }
}

final class EventContinuationBox: @unchecked Sendable {
    var continuation: AsyncStream<BackendEvent>.Continuation?
}

final class WeakBackend: @unchecked Sendable {
    weak var value: BackendClient?
    init(_ value: BackendClient) { self.value = value }
}

enum BackendEvent {
    case notification(method: String, params: JSONValue?)
    case request(id: RPCID, method: String, params: JSONValue?)
}

enum BackendError: Error, CustomStringConvertible {
    case notRunning
    case invalidResponse
    case rpc(String)

    var description: String {
        switch self {
        case .notRunning: return "backend not running"
        case .invalidResponse: return "invalid backend response"
        case .rpc(let message): return message
        }
    }
}

struct BackendRequest<P: Encodable>: Encodable {
    let jsonrpc = "2.0"
    let id: Int
    let method: String
    let params: P
}

struct BackendNotification<P: Encodable>: Encodable {
    let jsonrpc = "2.0"
    let method: String
    let params: P
}

struct BackendResponse<R: Encodable>: Encodable {
    let jsonrpc = "2.0"
    let id: RPCID
    let result: R
}

struct BackendIncoming: Decodable {
    let id: RPCID?
    let method: String?
    let params: JSONValue?
    let result: JSONValue?
    let error: BackendRPCError?
}

struct BackendRPCError: Decodable {
    let code: Int
    let message: String
}

enum RPCID: Codable, Hashable {
    case int(Int)
    case string(String)

    init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if let int = try? c.decode(Int.self) {
            self = .int(int)
        } else {
            self = .string(try c.decode(String.self))
        }
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.singleValueContainer()
        switch self {
        case .int(let int): try c.encode(int)
        case .string(let string): try c.encode(string)
        }
    }
}

struct InitializeClientInfo: Encodable {
    let name: String
    let title: String?
    let version: String
}

struct InitializeCapabilities: Encodable {
    let experimentalApi: Bool?
    let optOutNotificationMethods: [String]?
}

struct InitializeParams: Encodable {
    let clientInfo: InitializeClientInfo
    let capabilities: InitializeCapabilities?
}

struct EmptyObject: Encodable {}
struct EmptyResponse: Decodable {}

struct ThreadStartParams: Encodable {
    let cwd: String?
    let model: String?
    let approvalPolicy: String?
    let sandbox: String?
    let personality: String?
    let serviceTier: String?
    let collaborationMode: CollaborationModePayload?
}

struct ThreadHandle: Decodable {
    let id: String
    let cwd: String?
    let createdAt: String?
    let cliVersion: String?

    enum CodingKeys: String, CodingKey {
        case id, cwd, createdAt, cliVersion
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(String.self, forKey: .id)
        cwd = try c.decodeIfPresent(String.self, forKey: .cwd)
        cliVersion = try c.decodeIfPresent(String.self, forKey: .cliVersion)
        if let s = try? c.decodeIfPresent(String.self, forKey: .createdAt) {
            createdAt = s
        } else if let d = try? c.decodeIfPresent(Double.self, forKey: .createdAt) {
            createdAt = String(d)
        } else {
            createdAt = nil
        }
    }
}

struct ThreadStartResult: Decodable {
    let thread: ThreadHandle
    let model: String?
}

struct ThreadArchiveParams: Encodable {
    let threadId: String
}

struct ThreadUnarchiveParams: Encodable {
    let threadId: String
}

struct ThreadSetNameParams: Encodable {
    let threadId: String
    let name: String
}

struct ThreadListParams: Encodable {
    let archived: Bool?
    let cursor: String?
    let cwd: String?
    let limit: Int?
    let modelProviders: [String]?
    let searchTerm: String?
    let sortDirection: String?
    let sortKey: String?
    let sourceKinds: [String]?
    let useStateDbOnly: Bool?
}

struct ThreadListResponse: Decodable {
    let data: [AgentThreadSummary]
    let nextCursor: String?
}

struct AgentThreadSummary: Decodable {
    let id: String
    let cwd: String?
    let name: String?
    let preview: String
    let path: String?
    let createdAt: Int64?
    let updatedAt: Int64
    let archived: Bool?

    var updatedDate: Date {
        Date(timeIntervalSince1970: TimeInterval(updatedAt))
    }
}

/// One element of `turn/start`'s `input` array. Codex's app-server
/// protocol accepts a small discriminated union of input items; we
/// support `text` for the prompt body and `localImage` for inline
/// image attachments materialized to temp files. Encoding is hand-
/// rolled because Swift's Codable derivation would emit both fields
/// for both cases.
enum TurnStartUserInput: Encodable {
    case text(String)
    case localImage(path: String)

    private enum Keys: String, CodingKey {
        case type, text, path
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.container(keyedBy: Keys.self)
        switch self {
        case .text(let body):
            try c.encode("text", forKey: .type)
            try c.encode(body, forKey: .text)
        case .localImage(let path):
            try c.encode("localImage", forKey: .type)
            try c.encode(path, forKey: .path)
        }
    }
}

struct CollaborationModePayload: Encodable {
    let mode: String
    let settings: CollaborationModeSettingsPayload
}

struct CollaborationModeSettingsPayload: Encodable {
    let model: String
    let developer_instructions: String?
    let reasoning_effort: String?
}

struct TurnStartParams: Encodable {
    let threadId: String
    let input: [TurnStartUserInput]
    let model: String?
    let effort: String?
    let serviceTier: String?
    let collaborationMode: CollaborationModePayload?
}

struct TurnStartResult: Decodable {
    let turn: TurnHandle
}

struct TurnInterruptParams: Encodable {
    let threadId: String
    let turnId: String
}

struct TurnHandle: Decodable {
    let id: String
}

struct TurnEnvelope: Decodable {
    let threadId: String
    let turn: TurnHandle
}

struct AgentMessageDelta: Decodable {
    let delta: String
    let itemId: String
    let threadId: String
    let turnId: String
}

struct ReasoningTextDelta: Decodable {
    let delta: String
    let itemId: String
    let threadId: String
    let turnId: String
}

struct ItemEnvelope: Decodable {
    let item: ItemPayload
    let threadId: String
    let turnId: String
}

struct ItemPayload: Decodable {
    let id: String
    let type: String
    let text: String?
}

struct ToolRequestUserInputResponse: Encodable {
    let answers: [String: ToolRequestUserInputAnswer]
}

struct ToolRequestUserInputAnswer: Encodable {
    let answers: [String]
}

indirect enum JSONValue: Codable, Equatable {
    case null
    case bool(Bool)
    case int(Int)
    case double(Double)
    case string(String)
    case array([JSONValue])
    case object([String: JSONValue])

    init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if c.decodeNil() { self = .null; return }
        if let value = try? c.decode(Bool.self) { self = .bool(value); return }
        if let value = try? c.decode(Int.self) { self = .int(value); return }
        if let value = try? c.decode(Double.self) { self = .double(value); return }
        if let value = try? c.decode(String.self) { self = .string(value); return }
        if let value = try? c.decode([JSONValue].self) { self = .array(value); return }
        if let value = try? c.decode([String: JSONValue].self) { self = .object(value); return }
        throw DecodingError.dataCorruptedError(in: c, debugDescription: "unsupported JSON value")
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.singleValueContainer()
        switch self {
        case .null: try c.encodeNil()
        case .bool(let value): try c.encode(value)
        case .int(let value): try c.encode(value)
        case .double(let value): try c.encode(value)
        case .string(let value): try c.encode(value)
        case .array(let value): try c.encode(value)
        case .object(let value): try c.encode(value)
        }
    }

    func decode<T: Decodable>(_ type: T.Type) throws -> T {
        let data = try JSONEncoder().encode(self)
        return try JSONDecoder().decode(T.self, from: data)
    }
}

enum RolloutHistory {
    static func read(path: URL, now: Date = Date()) -> (messages: [WireMessage], lastTurnInterrupted: Bool) {
        guard let text = try? String(contentsOf: path, encoding: .utf8) else {
            return ([], false)
        }
        var messages: [WireMessage] = []
        var lastEventAt: Date?
        var sawAgentWork = false
        var sawClose = true
        let iso = ISO8601DateFormatter()
        for line in text.split(separator: "\n") {
            guard let data = line.data(using: .utf8),
                  let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
            else { continue }
            if let ts = obj["timestamp"] as? String {
                lastEventAt = iso.date(from: ts)
            }
            guard obj["type"] as? String == "event_msg",
                  let payload = obj["payload"] as? [String: Any],
                  let type = payload["type"] as? String
            else { continue }
            switch type {
            case "user_message":
                if let message = payload["message"] as? String {
                    messages.append(WireMessage(
                        id: UUID().uuidString,
                        role: .user,
                        content: message,
                        streamingFinished: true,
                        timestamp: lastEventAt ?? now
                    ))
                    sawClose = true
                }
            case "agent_message":
                let message = (payload["message"] as? String) ?? (payload["text"] as? String) ?? ""
                messages.append(WireMessage(
                    id: UUID().uuidString,
                    role: .assistant,
                    content: message,
                    streamingFinished: true,
                    timestamp: lastEventAt ?? now
                ))
                sawAgentWork = true
                sawClose = false
            case "final_answer", "turn_completed":
                sawClose = true
            default:
                break
            }
        }
        let interrupted = sawAgentWork
            && !sawClose
            && lastEventAt.map { now.timeIntervalSince($0) > 30 } == true
        return (messages, interrupted)
    }
}

// MARK: - Inline audio attachments

/// Maps a MIME type from a bridge `transcribeAudio` frame to the file
/// extension WhisperKit's `AVAudioFile` decoder expects. The list is
/// the codec set the iPhone composer can produce out of the box.
private func audioExtension(mimeType: String) -> String {
    switch mimeType.lowercased() {
    case "audio/wav", "audio/x-wav", "audio/wave":     return "wav"
    case "audio/m4a", "audio/mp4", "audio/x-m4a":      return "m4a"
    case "audio/aac":                                  return "aac"
    case "audio/mpeg", "audio/mp3":                    return "mp3"
    case "audio/ogg", "audio/opus":                    return "ogg"
    case "audio/flac":                                 return "flac"
    case "audio/caf", "audio/x-caf":                   return "caf"
    default:                                           return "m4a"
    }
}

// `AttachmentSpooler` lives in ClawixCore so the macOS GUI bridge and
// this daemon share the same temp-file layout for inline image inputs.
