import XCTest
@testable import Clawix

final class ClawJSRuntimeLensDomainPresentationTests: XCTestCase {
    func testRuntimeLensCommandMatrixAndDomainPresentations() async throws {
        let snapshot = try await ClawJSRuntimeLensTestFixtures.degradedRuntimePortalSnapshot()

        XCTAssertEqual(snapshot.commands?.authority, "runtime_adapter")
        XCTAssertEqual(snapshot.commands?.resourceDomains, ClawJSRuntimeLensSnapshot.canonicalDomains)
        XCTAssertEqual(snapshot.commands?.executableByClawCli?.first?.command, "runtime example sessions list")
        XCTAssertEqual(snapshot.commands?.executableByClawCli?.first?.args, ["sessions", "list"])
        XCTAssertEqual(snapshot.commands?.executableByClawCli?.first { $0.command.contains("inject") }?.delegatesTo, "blocked until native inject contract")
        XCTAssertEqual(snapshot.commands?.executableByClawCli?.first { $0.command.contains("inject") }?.args?.count, 7)
        XCTAssertEqual(snapshot.commands?.executableByClawCli?.first { $0.command.contains("create") }?.wouldWriteRuntime, true)
        XCTAssertEqual(snapshot.commands?.executableByClawCli?.first { $0.command.contains("create") }?.args?.last, "<title>")
        XCTAssertEqual(snapshot.commands?.mutationPolicy, "Runtime-owned actions must delegate to the runtime adapter or be marked unsupported.")
        let commandPresentation = ClawJSRuntimeLensCommandMatrixPresentation.make(
            commands: try XCTUnwrap(snapshot.commands)
        )
        XCTAssertEqual(commandPresentation.executableCount, 11)
        XCTAssertEqual(commandPresentation.writesRuntimeCount, 0)
        XCTAssertEqual(commandPresentation.wouldWriteRuntimeCount, 1)
        XCTAssertEqual(commandPresentation.readLocalCount, 10)
        XCTAssertEqual(commandPresentation.argumentCommandCount, 11)
        XCTAssertEqual(commandPresentation.argumentCount, 47)
        XCTAssertEqual(commandPresentation.resourceDomainCount, ClawJSRuntimeLensSnapshot.canonicalDomains.count)
        XCTAssertEqual(commandPresentation.resourceDomainsLabel, "sessions, skills, memory, channels, providers")
        XCTAssertEqual(commandPresentation.rows.first?.command, "runtime example sessions create --title <title>")
        XCTAssertEqual(commandPresentation.rows.first?.writeDisposition, "blocked write")
        XCTAssertEqual(commandPresentation.rows.first?.argumentCount, 4)
        XCTAssertEqual(commandPresentation.rows.first?.argsLabel, "sessions, create, --title, <title>")
        XCTAssertTrue(commandPresentation.rows.first?.accessibilityLabel.contains("blocked write") == true)
        XCTAssertTrue(commandPresentation.rows.first?.accessibilityLabel.contains("arguments 4") == true)
        XCTAssertTrue(commandPresentation.accessibilityLabel.contains("Runtime command matrix"))
        XCTAssertTrue(commandPresentation.accessibilityLabel.contains("would write runtime 1"))
        XCTAssertTrue(commandPresentation.accessibilityLabel.contains("argument commands 11"))
        XCTAssertEqual(snapshot.domains.map(\.domain), ClawJSRuntimeLensSnapshot.canonicalDomains)
        XCTAssertEqual(snapshot.missingCanonicalDomains, [])
        let missingDomainPresentation = ClawJSRuntimeLensMissingDomainPresentation.make(domains: snapshot.domains)
        XCTAssertEqual(missingDomainPresentation.coverageStatus, "all_domains_accounted")
        XCTAssertEqual(missingDomainPresentation.presentDomainCount, ClawJSRuntimeLensSnapshot.canonicalDomains.count)
        XCTAssertEqual(missingDomainPresentation.missingDomainCount, 0)
        XCTAssertFalse(missingDomainPresentation.hasMissingDomains)
        XCTAssertTrue(missingDomainPresentation.accessibilityLabel.contains("all_domains_accounted"))
        let incompleteMissingDomainPresentation = ClawJSRuntimeLensMissingDomainPresentation.make(
            domains: Array(snapshot.domains.dropLast())
        )
        XCTAssertEqual(incompleteMissingDomainPresentation.coverageStatus, "semantic_lens_incomplete")
        XCTAssertEqual(incompleteMissingDomainPresentation.missingDomainCount, 1)
        XCTAssertEqual(incompleteMissingDomainPresentation.rows.first?.domain, "configuration")
        XCTAssertEqual(incompleteMissingDomainPresentation.rows.first?.displayLabel, "Config")
        XCTAssertEqual(incompleteMissingDomainPresentation.missingDomainsLabel, "configuration")
        XCTAssertTrue(incompleteMissingDomainPresentation.accessibilityLabel.contains("missing domains configuration"))
        XCTAssertEqual(snapshot.domains.first { $0.domain == "channels" }?.count, 7)
        XCTAssertEqual(snapshot.domains.first { $0.domain == "channels" }?.claim, "inventoried")
        XCTAssertEqual(snapshot.domains.first { $0.domain == "channels" }?.writeBackPolicy, "external_pending_live_accounts")
        XCTAssertEqual(snapshot.domains.first { $0.domain == "channels" }?.externalPending, true)
        XCTAssertEqual(snapshot.domains.first { $0.domain == "channels" }?.officialCommands?.first, "example gateway")
        let domainCommandPresentation = ClawJSRuntimeLensDomainCommandPresentation.make(
            domain: "channels",
            commands: snapshot.domains.first { $0.domain == "channels" }?.officialCommands ?? [],
            limit: 2
        )
        XCTAssertEqual(domainCommandPresentation.domain, "channels")
        XCTAssertEqual(domainCommandPresentation.totalCommandCount, 3)
        XCTAssertEqual(domainCommandPresentation.visibleCommandCount, 2)
        XCTAssertEqual(domainCommandPresentation.hiddenCommandCount, 1)
        XCTAssertEqual(domainCommandPresentation.rows.first?.command, "example gateway")
        XCTAssertEqual(domainCommandPresentation.rows.first?.id, "example-gateway")
        XCTAssertTrue(domainCommandPresentation.hasCommands)
        XCTAssertTrue(domainCommandPresentation.rows.first?.accessibilityLabel.contains("runtime domain command 1") == true)
        XCTAssertTrue(domainCommandPresentation.accessibilityLabel.contains("Runtime domain commands"))
        XCTAssertEqual(snapshot.domains.first { $0.domain == "channels" }?.evidenceRequirements?.first?.blockerClass, "external_pending")
        XCTAssertEqual(snapshot.domains.first { $0.domain == "channels" }?.evidenceRequirements?.first?.commandShape, "runtime example domain channels --json")
        XCTAssertEqual(snapshot.domains.first { $0.domain == "sandboxPermissions" }?.displayLabel, "Sandbox")
        let domainPresentation = ClawJSRuntimeLensDomainPresentation.make(domains: snapshot.domains)
        XCTAssertEqual(domainPresentation.domainCount, ClawJSRuntimeLensSnapshot.canonicalDomains.count)
        XCTAssertEqual(domainPresentation.unsupportedCount, 0)
        XCTAssertEqual(domainPresentation.externalPendingCount, 1)
        XCTAssertEqual(domainPresentation.evidenceRequirementCount, 1)
        XCTAssertEqual(domainPresentation.nativeCommandDomainCount, 1)
        XCTAssertEqual(domainPresentation.limitationDomainCount, 1)
        XCTAssertEqual(domainPresentation.limitationCount, 1)
        XCTAssertEqual(domainPresentation.policyDomainCount, 2)
        XCTAssertEqual(domainPresentation.writeBackAllowedCount, 0)
        XCTAssertEqual(domainPresentation.provenanceDomainCount, 2)
        XCTAssertEqual(domainPresentation.strategyLabel, "cli 1, gateway 1, hosted 1, native 10")
        XCTAssertEqual(domainPresentation.persistenceLabel, "index_and_shadow_when_safe 1, secret_refs_only 1")
        XCTAssertEqual(domainPresentation.validationLabel, "external_pending_for_live_accounts 1, fixture_required 1")
        XCTAssertEqual(domainPresentation.provenanceSourceLabel, "runtime-ecosystem-manifest 2")
        XCTAssertTrue(domainPresentation.statusLabel?.contains("error 1") == true)
        XCTAssertEqual(domainPresentation.externalPendingDomainsLabel, "channels")
        XCTAssertEqual(domainPresentation.limitationDomainsLabel, "channels")
        let channelPresentation = try XCTUnwrap(domainPresentation.rows.first { $0.domain == "channels" })
        XCTAssertEqual(channelPresentation.displayLabel, "Channels")
        XCTAssertEqual(channelPresentation.status, "degraded")
        XCTAssertEqual(channelPresentation.strategy, "native")
        XCTAssertEqual(channelPresentation.claim, "inventoried")
        XCTAssertEqual(channelPresentation.count, 7)
        XCTAssertEqual(channelPresentation.nativeAuthority, "runtime")
        XCTAssertEqual(channelPresentation.persistence, "secret_refs_only")
        XCTAssertEqual(channelPresentation.relation, "gateway_projection")
        XCTAssertEqual(channelPresentation.lossPolicy, "secret_refs_only")
        XCTAssertEqual(channelPresentation.writeBackPolicy, "external_pending_live_accounts")
        XCTAssertEqual(channelPresentation.writeBackAllowed, false)
        XCTAssertEqual(channelPresentation.validation, "external_pending_for_live_accounts")
        XCTAssertEqual(channelPresentation.provenanceSource, "runtime-ecosystem-manifest")
        XCTAssertEqual(channelPresentation.provenanceRuntimeId, "example")
        XCTAssertEqual(channelPresentation.provenanceDomain, "channels")
        XCTAssertEqual(
            channelPresentation.policyLabel,
            "native runtime, persistence secret_refs_only, relation gateway_projection, loss secret_refs_only, validation external_pending_for_live_accounts, no runtime write-back"
        )
        XCTAssertEqual(
            channelPresentation.provenanceLabel,
            "runtime-ecosystem-manifest, runtime example, domain channels"
        )
        XCTAssertEqual(channelPresentation.commandCount, 3)
        XCTAssertEqual(channelPresentation.evidenceRequirementCount, 1)
        XCTAssertEqual(channelPresentation.limitationCount, 1)
        XCTAssertEqual(channelPresentation.limitationsLabel, "normalized")
        XCTAssertTrue(channelPresentation.accessibilityLabel.contains("external pending true"))
        XCTAssertTrue(channelPresentation.accessibilityLabel.contains("strategy native"))
        XCTAssertTrue(channelPresentation.accessibilityLabel.contains("native authority runtime"))
        XCTAssertTrue(channelPresentation.accessibilityLabel.contains("persistence secret_refs_only"))
        XCTAssertTrue(channelPresentation.accessibilityLabel.contains("write back allowed false"))
        XCTAssertTrue(channelPresentation.accessibilityLabel.contains("validation external_pending_for_live_accounts"))
        XCTAssertTrue(channelPresentation.accessibilityLabel.contains("limitations normalized"))
        XCTAssertTrue(channelPresentation.accessibilityLabel.contains("provenance source runtime-ecosystem-manifest"))
        XCTAssertTrue(channelPresentation.accessibilityLabel.contains("provenance runtime example"))
        XCTAssertTrue(channelPresentation.accessibilityLabel.contains("provenance domain channels"))
        XCTAssertTrue(domainPresentation.accessibilityLabel.contains("strategies cli 1, gateway 1, hosted 1, native 10"))
        XCTAssertTrue(domainPresentation.accessibilityLabel.contains("policy domains 2"))
        XCTAssertTrue(domainPresentation.accessibilityLabel.contains("provenance domains 2"))
        XCTAssertTrue(domainPresentation.accessibilityLabel.contains("persistence index_and_shadow_when_safe 1, secret_refs_only 1"))
        XCTAssertTrue(domainPresentation.accessibilityLabel.contains("validation external_pending_for_live_accounts 1, fixture_required 1"))
        XCTAssertTrue(domainPresentation.accessibilityLabel.contains("provenance sources runtime-ecosystem-manifest 2"))
        XCTAssertTrue(domainPresentation.accessibilityLabel.contains("limitation domains channels"))
        let domainEvidencePresentation = ClawJSRuntimeLensEvidenceRequirementPresentation.make(
            requirements: channelPresentation.evidenceRequirements,
            limit: 2
        )
        XCTAssertEqual(domainEvidencePresentation.totalRequirementCount, 1)
        XCTAssertEqual(domainEvidencePresentation.externalPendingCount, 1)
        XCTAssertEqual(domainEvidencePresentation.rows.first?.commandShape, "runtime example domain channels --json")
        XCTAssertTrue(domainEvidencePresentation.rows.first?.accessibilityLabel.contains("evidence requirement example.channels.live_evidence") == true)
        XCTAssertTrue(domainEvidencePresentation.accessibilityLabel.contains("Runtime evidence requirements"))
        XCTAssertTrue(domainPresentation.accessibilityLabel.contains("Runtime domains"))
    }
}
