import XCTest
@testable import Clawix

final class ClawJSRuntimeLensRuntimeSummaryTests: XCTestCase {
    func testRuntimeLensRuntimeSummaryPresentsStatusWorkspaceAndCapabilities() async throws {
        let snapshot = try await ClawJSRuntimeLensTestFixtures.degradedRuntimePortalSnapshot()

        XCTAssertEqual(snapshot.runtimeId, "hermes")
        XCTAssertEqual(snapshot.status.cliAvailable, false)
        XCTAssertEqual(snapshot.status.diagnostics?.locations?.homeDir, "/Users/tester/.hermes")
        let runtimeSummaryPresentation = ClawJSRuntimeLensRuntimeSummaryPresentation.make(snapshot: snapshot)
        XCTAssertEqual(runtimeSummaryPresentation.runtimeId, "hermes")
        XCTAssertEqual(runtimeSummaryPresentation.runtimeName, "Hermes Agent")
        XCTAssertEqual(snapshot.status.adapter, "hermes")
        XCTAssertEqual(snapshot.status.version, "1.2.3")
        XCTAssertEqual(snapshot.status.capabilities?["conversationCli"], true)
        XCTAssertEqual(snapshot.status.capabilityMap?["runtime"]?.diagnostics?.source, "runtime")
        XCTAssertEqual(snapshot.status.capabilityMap?["channels"]?.limitations?.first, "Channel inventory is normalized from Hermes gateway capabilities.")
        XCTAssertEqual(snapshot.session?.sessionPath, "/Users/tester/.hermes/sessions")
        XCTAssertEqual(snapshot.session?.primaryTransport, "gateway")
        XCTAssertEqual(snapshot.workspace?.canonicalPaths?["SOUL"], "/tmp/workspace/SOUL.md")
        XCTAssertEqual(snapshot.workspace?.managedFiles?.count, 2)
        XCTAssertEqual(runtimeSummaryPresentation.adapter, "hermes")
        XCTAssertEqual(runtimeSummaryPresentation.version, "1.2.3")
        XCTAssertEqual(runtimeSummaryPresentation.installed, false)
        XCTAssertEqual(runtimeSummaryPresentation.installedLabel, "Not installed")
        XCTAssertEqual(runtimeSummaryPresentation.cliLabel, "Unavailable")
        XCTAssertEqual(runtimeSummaryPresentation.gatewayLabel, "Degraded")
        XCTAssertEqual(runtimeSummaryPresentation.homeDir, "/Users/tester/.hermes")
        XCTAssertEqual(runtimeSummaryPresentation.workspacePath, "/tmp/workspace")
        XCTAssertEqual(runtimeSummaryPresentation.configPath, "/Users/tester/.hermes/config.json")
        XCTAssertEqual(runtimeSummaryPresentation.authStorePath, "/Users/tester/.hermes/auth.json")
        XCTAssertEqual(runtimeSummaryPresentation.gatewayConfigPath, "/Users/tester/.hermes/gateway.json")
        XCTAssertEqual(runtimeSummaryPresentation.locationRows.map(\.id), ["home", "workspace", "config", "auth-store", "gateway-config"])
        XCTAssertEqual(runtimeSummaryPresentation.locationRows.first?.accessibilityLabel, "Home /Users/tester/.hermes")
        XCTAssertEqual(runtimeSummaryPresentation.locationCount, 5)
        XCTAssertEqual(runtimeSummaryPresentation.workspaceCanonicalPathCount, 3)
        XCTAssertEqual(runtimeSummaryPresentation.workspaceManagedFileCount, 2)
        XCTAssertEqual(runtimeSummaryPresentation.workspaceFilesLabel, "canonical SKILLS, SOUL, USER; managed 2")
        XCTAssertEqual(runtimeSummaryPresentation.lastError, "hermes CLI not found")
        XCTAssertEqual(runtimeSummaryPresentation.hasHomeDir, true)
        XCTAssertEqual(runtimeSummaryPresentation.hasLastError, true)
        XCTAssertEqual(runtimeSummaryPresentation.supportPresent, true)
        XCTAssertEqual(runtimeSummaryPresentation.supportAuditPresent, true)
        XCTAssertEqual(runtimeSummaryPresentation.rawCapabilityCount, 3)
        XCTAssertEqual(runtimeSummaryPresentation.rawCapabilityEnabledCount, 1)
        XCTAssertEqual(runtimeSummaryPresentation.capabilityCount, 4)
        XCTAssertEqual(runtimeSummaryPresentation.readyCapabilityCount, 1)
        XCTAssertEqual(runtimeSummaryPresentation.degradedCapabilityCount, 1)
        XCTAssertEqual(runtimeSummaryPresentation.errorCapabilityCount, 1)
        XCTAssertEqual(runtimeSummaryPresentation.unsupportedCapabilityCount, 1)
        XCTAssertEqual(runtimeSummaryPresentation.capabilityStatusLabel, "degraded 1, error 1, ready 1, unsupported 1")
        XCTAssertEqual(runtimeSummaryPresentation.capabilityRows.map(\.id), ["channels", "plugins", "runtime", "workspace"])
        XCTAssertEqual(runtimeSummaryPresentation.capabilityRows.first?.limitationsLabel, "Channel inventory is normalized from Hermes gateway capabilities.")
        XCTAssertTrue(runtimeSummaryPresentation.capabilityRows.first?.accessibilityLabel.contains("strategy native") == true)
        XCTAssertTrue(runtimeSummaryPresentation.accessibilityLabel.contains("Runtime summary"))
        XCTAssertTrue(runtimeSummaryPresentation.accessibilityLabel.contains("adapter hermes"))
        XCTAssertTrue(runtimeSummaryPresentation.accessibilityLabel.contains("version 1.2.3"))
        XCTAssertTrue(runtimeSummaryPresentation.accessibilityLabel.contains("workspace canonical paths 3"))
        XCTAssertTrue(runtimeSummaryPresentation.accessibilityLabel.contains("workspace files canonical SKILLS, SOUL, USER; managed 2"))
        XCTAssertTrue(runtimeSummaryPresentation.accessibilityLabel.contains("raw capabilities 3"))
        XCTAssertTrue(runtimeSummaryPresentation.accessibilityLabel.contains("capability status degraded 1, error 1, ready 1, unsupported 1"))
        XCTAssertTrue(runtimeSummaryPresentation.accessibilityLabel.contains("Workspace /tmp/workspace"))
        XCTAssertTrue(runtimeSummaryPresentation.accessibilityLabel.contains("Gateway config /Users/tester/.hermes/gateway.json"))
        XCTAssertTrue(runtimeSummaryPresentation.accessibilityLabel.contains("support audit true"))
        XCTAssertEqual(snapshot.support?.ecosystem?.evidenceRequirements?.first?.id, "hermes.channels.live_evidence")
        XCTAssertEqual(snapshot.support?.ecosystem?.evidenceRequirements?.first?.approvalRequired, true)
        XCTAssertEqual(snapshot.support?.ecosystem?.evidenceRequirements?.first?.evidenceDisposition, "external_pending_until_approved_redacted_live_receipt")
        XCTAssertEqual(snapshot.support?.ecosystem?.evidenceRequirements?.first?.currentBehavior, "read_only_projection_or_degraded_snapshot_only")
        XCTAssertEqual(snapshot.support?.ecosystem?.claimSource, "runtime-ecosystem-manifest")
        XCTAssertEqual(snapshot.support?.ecosystem?.provenance?.source, "runtime-ecosystem-manifest")
        XCTAssertEqual(snapshot.support?.ecosystem?.provenance?.runtimeId, "hermes")
    }
}
