import XCTest
@testable import Clawix

@MainActor
final class RepositoryDatabaseFallbackTests: XCTestCase {
    func testLocalRepositoriesReturnDefaultsWhenDatabaseUnavailable() {
        let projects = ProjectsRepository(dbProvider: { nil })
        let orders = ProjectOrdersRepository(dbProvider: { nil })
        let pins = PinsRepository(dbProvider: { nil })
        let chatProjects = ChatProjectsRepository(dbProvider: { nil })
        let meta = MetaRepository(dbProvider: { nil })
        let archives = ArchivesRepository(dbProvider: { nil })
        let hiddenRoots = HiddenRootsRepository(dbProvider: { nil })
        let titles = SessionTitlesRepository(dbProvider: { nil })
        let snapshots = SnapshotRepository(dbProvider: { nil })

        XCTAssertEqual(projects.count(), 0)
        XCTAssertEqual(projects.all(), [])
        XCTAssertEqual(orders.orderedIds(), [])
        XCTAssertEqual(pins.count(), 0)
        XCTAssertEqual(pins.orderedThreadIds(), [])
        XCTAssertFalse(pins.isPinned("thread"))
        XCTAssertEqual(chatProjects.overridesCount(), 0)
        XCTAssertEqual(chatProjects.projectlessCount(), 0)
        XCTAssertEqual(chatProjects.allOverrides(), [:])
        XCTAssertNil(chatProjects.overridePath(for: "thread"))
        XCTAssertNil(meta.string(forKey: "key"))
        XCTAssertFalse(meta.boolValue(forKey: "key"))
        XCTAssertEqual(archives.count(), 0)
        XCTAssertFalse(archives.isArchived("thread"))
        XCTAssertEqual(archives.allArchived(), [])
        XCTAssertEqual(hiddenRoots.count(), 0)
        XCTAssertFalse(hiddenRoots.isHidden("/tmp/example"))
        XCTAssertEqual(hiddenRoots.allHidden(), [])
        XCTAssertEqual(titles.count(), 0)
        XCTAssertNil(titles.title(for: "thread"))
        XCTAssertEqual(snapshots.count(), 0)
        XCTAssertTrue(snapshots.loadTop(limit: 10).isEmpty)
        XCTAssertTrue(snapshots.loadAllProjectIndexed().isEmpty)
        XCTAssertEqual(snapshots.projectPathHints(), [])
    }

    func testWritesDoNotCrashWhenDatabaseUnavailable() {
        let projects = ProjectsRepository(dbProvider: { nil })
        let pins = PinsRepository(dbProvider: { nil })
        let chatProjects = ChatProjectsRepository(dbProvider: { nil })
        let meta = MetaRepository(dbProvider: { nil })
        let archives = ArchivesRepository(dbProvider: { nil })
        let hiddenRoots = HiddenRootsRepository(dbProvider: { nil })
        let titles = SessionTitlesRepository(dbProvider: { nil })

        projects.upsert(Project(name: "Test", path: "/tmp/test"))
        projects.rename(id: UUID(), to: "Renamed")
        projects.delete(id: UUID())
        pins.setPinned("thread")
        pins.unpin("thread")
        pins.setOrder(["thread"])
        XCTAssertEqual(pins.addIfMissing(["thread"]), 0)
        chatProjects.setOverride(threadId: "thread", projectPath: "/tmp/test")
        chatProjects.clearOverride(threadId: "thread")
        chatProjects.markProjectless("thread")
        chatProjects.unmarkProjectless("thread")
        meta.setString("value", forKey: "key")
        meta.setBool(true, forKey: "flag")
        archives.archive("thread")
        archives.unarchive("thread")
        archives.bulkArchive(["thread"])
        archives.bulkUnarchive(["thread"])
        hiddenRoots.hide("/tmp/test")
        hiddenRoots.show("/tmp/test")
        titles.upsertManual(threadId: "thread", title: "Title")
        titles.upsertGenerated(threadId: "thread", title: "Generated")
    }
}
