import Foundation

/// Resolves the per-session admin token used to authenticate against the
/// bundled `@clawjs/database` daemon over loopback. Replaces the previous
/// `DatabaseKeychain` so the app never touches the system Keychain.
///
/// Resolution order:
///   1. The token generated by `ClawJSServiceManager` for this process and
///      injected into the daemon via `CLAWJS_DATABASE_ADMIN_TOKEN` (when
///      the GUI spawned the daemon).
///   2. The 0600 file `<data-dir>/.admin-token` written by the owner that
///      launched the daemon (when this process connects to an existing
///      Clawix-owned sidecar).
@MainActor
enum DatabaseAdminToken {
    static func currentAdminToken() throws -> String {
        if let token = ClawJSServiceManager.shared.adminTokenIfSpawned(for: .database) {
            return token
        }
        return try ClawJSServiceManager.adminTokenFromDataDir(for: .database)
    }
}
