import Foundation

/// Resolves the per-session admin token used to authenticate against the
/// bundled `@clawjs/database` daemon over loopback. Replaces the previous
/// `DatabaseKeychain` so the app never touches the system Keychain.
///
/// Resolution order:
///   1. The token generated by `ClawJSServiceManager` for this process and
///      bootstrapped into the daemon over anonymous stdin.
@MainActor
enum DatabaseAdminToken {
    static func currentAdminToken() throws -> String {
        if let token = ClawJSServiceManager.shared.adminTokenIfSpawned(for: .database) {
            return token
        }
        return try ClawJSServiceManager.adminTokenFromDataDir(for: .database)
    }
}
