import Foundation
import AVFoundation
import ClawixCore

/// Persistent metadata for a voice clip the iPhone (or any future
/// audio-capable client) shipped along with a user message. The bytes
/// live next to this entry on disk; clients fetch them on first replay
/// via the `requestAudio` bridge frame and cache locally.
///
/// `transcript` is also stored on disk so a daemon restart that
/// rebuilds chat history from the rollout can re-match audio entries
/// to their user messages by content equality and chronological order
/// (rollouts mint a fresh message id on rebuild, so we can't key by
/// messageId alone).
public struct AudioStoreEntry: Codable, Equatable, Sendable {
    public let id: String
    public let threadId: String
    public let chatId: String
    public let messageId: String
    public let transcript: String
    public let mimeType: String
    public let durationMs: Int
    public let fileRelPath: String
    public let createdAt: Date

    public init(
        id: String,
        threadId: String,
        chatId: String,
        messageId: String,
        transcript: String,
        mimeType: String,
        durationMs: Int,
        fileRelPath: String,
        createdAt: Date
    ) {
        self.id = id
        self.threadId = threadId
        self.chatId = chatId
        self.messageId = messageId
        self.transcript = transcript
        self.mimeType = mimeType
        self.durationMs = durationMs
        self.fileRelPath = fileRelPath
        self.createdAt = createdAt
    }

    /// Wire-shaped pointer the bridge sends to clients alongside a
    /// user message. The transcript stays in `WireMessage.content`;
    /// the ref only carries what clients need to draw the bubble and
    /// fetch the bytes on first replay.
    public var wireRef: WireAudioRef {
        WireAudioRef(id: id, mimeType: mimeType, durationMs: durationMs)
    }
}

/// On-disk store for voice clips attached to user messages. Owned by
/// whichever process holds the chat backend (the macOS GUI's
/// `AppState` in in-process mode, or `clawix-bridged` in daemon mode).
/// The actor is the only writer; readers go through the public async
/// API so concurrent calls from the bridge thread don't race.
///
/// On-disk layout:
///   <root>/audio/<chatId>/<audioId>.<ext>     bytes (m4a / wav / etc.)
///   <root>/audio-meta.json                    array of `AudioStoreEntry`
public actor AudioMessageStore {

    public static let shared = AudioMessageStore()

    private let storeRoot: URL
    private let metaURL: URL
    private var entries: [AudioStoreEntry] = []
    private var loaded = false

    /// Default location: `~/Library/Application Support/Clawix/`.
    /// Both the GUI and the daemon resolve to the same path because
    /// `applicationSupportDirectory` is per-user and neither process is
    /// sandboxed (the daemon ships with com.apple.security.app-sandbox
    /// off so the LaunchAgent can read the rollout dir).
    public init() {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
            ?? URL(fileURLWithPath: NSHomeDirectory())
                .appendingPathComponent("Library/Application Support", isDirectory: true)
        let clawix = base.appendingPathComponent("Clawix", isDirectory: true)
        self.storeRoot = clawix.appendingPathComponent("audio", isDirectory: true)
        self.metaURL = clawix.appendingPathComponent("audio-meta.json")
    }

    /// Override the root for tests so we don't pollute the real
    /// Application Support tree. The store keeps the same nested layout.
    public init(rootForTesting root: URL) {
        self.storeRoot = root.appendingPathComponent("audio", isDirectory: true)
        self.metaURL = root.appendingPathComponent("audio-meta.json")
    }

    // MARK: - Public API

    /// Save a voice clip to disk and append a metadata entry. Returns
    /// the entry so the caller can attach `audioRef` to the user
    /// message it's about to enqueue. `audioId` is generated by the
    /// store so callers don't have to coordinate UUIDs across layers.
    @discardableResult
    public func ingest(
        threadId: String,
        chatId: String,
        messageId: String,
        audioData: Data,
        mimeType: String,
        transcript: String
    ) async throws -> AudioStoreEntry {
        await ensureLoaded()
        let audioId = UUID().uuidString
        let ext = AudioMessageStore.fileExtension(for: mimeType)
        let chatDir = storeRoot.appendingPathComponent(chatId, isDirectory: true)
        let fileURL = chatDir.appendingPathComponent("\(audioId).\(ext)")
        try FileManager.default.createDirectory(at: chatDir, withIntermediateDirectories: true)
        try audioData.write(to: fileURL, options: .atomic)
        let durationMs = AudioMessageStore.durationMs(of: fileURL)
        let entry = AudioStoreEntry(
            id: audioId,
            threadId: threadId,
            chatId: chatId,
            messageId: messageId,
            transcript: transcript,
            mimeType: mimeType,
            durationMs: durationMs,
            fileRelPath: "\(chatId)/\(audioId).\(ext)",
            createdAt: Date()
        )
        entries.append(entry)
        try saveMeta()
        return entry
    }

    public func entry(forAudioId id: String) async -> AudioStoreEntry? {
        await ensureLoaded()
        return entries.first { $0.id == id }
    }

    /// Entries belonging to a thread, ordered by `createdAt`. Used by
    /// the daemon's hydrate path to re-attach audio refs to messages
    /// rebuilt from the rollout.
    public func entries(forThread threadId: String) async -> [AudioStoreEntry] {
        await ensureLoaded()
        return entries.filter { $0.threadId == threadId }
            .sorted { $0.createdAt < $1.createdAt }
    }

    /// Load the bytes of a stored clip. Returns nil if the file
    /// disappeared (manual deletion, disk pressure cleanup) so the
    /// caller can surface a friendly "Audio no longer available" error.
    public func data(forAudioId id: String) async -> (data: Data, mimeType: String)? {
        await ensureLoaded()
        guard let entry = entries.first(where: { $0.id == id }) else { return nil }
        let url = storeRoot.appendingPathComponent(entry.fileRelPath)
        guard let data = try? Data(contentsOf: url) else { return nil }
        return (data, entry.mimeType)
    }

    // MARK: - Helpers

    private func ensureLoaded() async {
        guard !loaded else { return }
        loaded = true
        guard let data = try? Data(contentsOf: metaURL) else { return }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        if let decoded = try? decoder.decode([AudioStoreEntry].self, from: data) {
            entries = decoded
        }
    }

    private func saveMeta() throws {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        encoder.outputFormatting = [.prettyPrinted]
        let data = try encoder.encode(entries)
        try FileManager.default.createDirectory(
            at: metaURL.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try data.write(to: metaURL, options: .atomic)
    }

    /// MIME → file extension mapping covering the codec set the iPhone
    /// composer can produce (m4a/AAC default) plus the alternates the
    /// dictation flow already accepts. Unknown types fall back to .m4a
    /// because that's what AVAudioRecorder writes by default.
    public static func fileExtension(for mimeType: String) -> String {
        switch mimeType.lowercased() {
        case "audio/wav", "audio/x-wav", "audio/wave":     return "wav"
        case "audio/m4a", "audio/mp4", "audio/x-m4a":      return "m4a"
        case "audio/aac":                                  return "aac"
        case "audio/mpeg", "audio/mp3":                    return "mp3"
        case "audio/ogg", "audio/opus":                    return "ogg"
        case "audio/flac":                                 return "flac"
        case "audio/caf", "audio/x-caf":                   return "caf"
        default:                                           return "m4a"
        }
    }

    /// Reads duration off the file with the legacy synchronous API.
    /// `AVAudioFile` works on every macOS / iOS version we ship to and
    /// avoids the await-only `load(.duration)` path so the call stays
    /// usable from a synchronous context (the actor's `ingest` builds
    /// the entry inline). For voice notes the read is a few hundred
    /// microseconds: AVAudioFile only parses the header.
    private static func durationMs(of url: URL) -> Int {
        guard let file = try? AVAudioFile(forReading: url) else { return 0 }
        let frames = Double(file.length)
        let sampleRate = file.processingFormat.sampleRate
        guard sampleRate > 0 else { return 0 }
        let seconds = frames / sampleRate
        guard seconds.isFinite, seconds > 0 else { return 0 }
        return Int((seconds * 1000).rounded())
    }
}
