import Foundation
#if canImport(Combine)
import Combine
#else
import OpenCombine
import OpenCombineFoundation
#endif
import ClawixCore
import ClawixEngine
#if canImport(WhisperKit)
import WhisperKit
#endif

@main
struct BridgeMain {
    static func main() {
        // Maintenance flag: `clawix-bridge --download-model <variant>`
        // pulls a WhisperKit model under `~/Documents/huggingface/models/...`
        // and exits. Used by `dev.sh` to recover a corrupted/incomplete
        // cache without forcing the user through the GUI Settings flow.
        // Variant matches `DictationModel.rawValue` (`large-v3`,
        // `large-v3_turbo`).
        let argv = CommandLine.arguments
        if argv.count >= 3, argv[1] == "--download-model" {
            #if canImport(WhisperKit)
            let variant = argv[2]
            let semaphore = DispatchSemaphore(value: 0)
            Task {
                do {
                    let url = try await WhisperKit.download(
                        variant: variant,
                        progressCallback: { progress in
                            let pct = Int(progress.fractionCompleted * 100)
                            FileHandle.standardError.write(
                                Data("download \(variant): \(pct)%\n".utf8)
                            )
                        }
                    )
                    FileHandle.standardError.write(
                        Data("download \(variant) ok at \(url.path)\n".utf8)
                    )
                } catch {
                    FileHandle.standardError.write(
                        Data("download \(variant) failed: \(error)\n".utf8)
                    )
                    exit(1)
                }
                semaphore.signal()
            }
            semaphore.wait()
            exit(0)
            #else
            FileHandle.standardError.write(
                Data("--download-model is not available on this platform; use whisper.cpp instead\n".utf8)
            )
            exit(2)
            #endif
        }

        BridgeLog.write("starting schemaVersion=\(bridgeSchemaVersion)")
        let env = ProcessInfo.processInfo.environment
        let port = env["CLAWIX_BRIDGE_PORT"].flatMap(UInt16.init) ?? 24080
        let httpPort = env["CLAWIX_BRIDGE_HTTP_PORT"].flatMap(UInt16.init) ?? 24081
        let defaults = env["CLAWIX_BRIDGE_DEFAULTS_SUITE"]
            .flatMap { UserDefaults(suiteName: $0) }
            ?? .standard
        if let bearer = env["CLAWIX_BRIDGE_BEARER"], !bearer.isEmpty {
            defaults.set(bearer, forKey: "ClawixBridge.Bearer.v1")
        }
        let pairing = PairingService(defaults: defaults, port: port)
        // Force the bearer + short code to materialize at startup so
        // external surfaces (the npm CLI's `clawix pair`, the menubar
        // helper, a future iOS app reading the suite directly) can pull
        // the QR payload without first opening a websocket. Both are
        // lazily generated by their getters; touching them once writes
        // to UserDefaults if not already there.
        _ = pairing.bearer
        _ = pairing.shortCode
        let publishBonjour = env["CLAWIX_BRIDGE_DISABLE_BONJOUR"] != "1"
        let box = HostBox()
        BridgeHeartbeat.start(port: port, hostBox: box)

        Task { @MainActor in
            let runtime = AgentRuntimeSelection.resolve(environment: env, defaults: defaults)
            switch runtime {
            case .codex:
                guard let binary = BackendBinary.resolve(environment: env) else {
                    BridgeLog.write("backend binary not found")
                    exit(78)
                }
                let host = DaemonEngineHost(binary: binary, pairing: pairing)
                let meshStore = RemoteMeshStore()
                let meshIdentity = RemoteMeshIdentity(root: meshStore.root)
                let mesh = RemoteMeshHTTPController(
                    identity: meshIdentity,
                    store: meshStore,
                    host: host,
                    pairing: pairing,
                    bridgePort: port,
                    httpPort: httpPort
                )
                let server = BridgeServer(
                    host: host,
                    port: port,
                    pairing: pairing,
                    publishBonjour: publishBonjour
                )
                server.start()
                box.host = host
                box.server = server
                BridgeLog.write("listening tcp/\(port) runtime=codex backend=\(binary.path.path)")
                let webServer = WebStaticServer(httpPort: httpPort, wsPort: port, pairing: pairing, mesh: mesh)
                webServer.start()
                box.webServer = webServer
                Task { @MainActor in
                    await host.bootstrap()
                }
            case .opencode:
                let host = OpenCodeDaemonEngineHost(pairing: pairing, defaults: defaults, environment: env)
                let server = BridgeServer(
                    host: host,
                    port: port,
                    pairing: pairing,
                    publishBonjour: publishBonjour
                )
                server.start()
                box.host = host
                box.server = server
                BridgeLog.write("listening tcp/\(port) runtime=opencode")
                let webServer = WebStaticServer(httpPort: httpPort, wsPort: port, pairing: pairing)
                webServer.start()
                box.webServer = webServer
                Task { @MainActor in
                    await host.bootstrap()
                }
            }
        }

        RunLoop.current.run()
    }
}

final class HostBox: @unchecked Sendable {
    var host: AnyObject?
    var server: AnyObject?
    var webServer: AnyObject?

    /// Read snapshot of host state, decoupled from the host's
    /// MainActor isolation so the heartbeat timer (which runs on a
    /// utility queue) can pull it without hopping actors. Returns
    /// defaults when the host hasn't been wired yet.
    struct Snapshot: Sendable {
        let state: String
        let chatCount: Int
        let lastSyncAt: Date?
        let errorMessage: String?
    }

    func snapshot() -> Snapshot {
        guard let host = host as? DaemonEngineHost else {
            return Snapshot(state: "booting", chatCount: 0, lastSyncAt: nil, errorMessage: nil)
        }
        // The heartbeat timer is `nonisolated` for performance, so we
        // do a fast `MainActor.assumeIsolated` read. Reading a few
        // ivars is cheap and the heartbeat fires on a low-priority
        // queue; falling back to defaults if the assume fails keeps
        // the writer non-blocking.
        return MainActor.assumeIsolated {
            Snapshot(
                state: host.bridgeStateCurrent.wireTag,
                chatCount: host.bridgeChatsCurrent.count,
                lastSyncAt: host.lastChatsPublishedAt,
                errorMessage: host.bridgeStateCurrent.errorMessage
            )
        }
    }
}

/// Periodic heartbeat to a tiny JSON file under
/// `~/.clawix/state/bridge-status.json`. The npm CLI reads this file
/// to drive `clawix status` and the live watch in `clawix up` without
/// opening an authenticated websocket. Atomic write (`.tmp` + rename)
/// so a reader never sees a half-flushed JSON. peerCount stays 0 in
/// this iteration; wiring it to `BridgeServer` lives in v1.x.
enum BridgeHeartbeat {
    private static let interval: TimeInterval = 2.0

    static func start(port: UInt16, hostBox: HostBox) {
        let queue = DispatchQueue(label: "com.clawix.bridge.heartbeat", qos: .utility)
        let timer = DispatchSource.makeTimerSource(queue: queue)
        timer.schedule(deadline: .now(), repeating: interval, leeway: .milliseconds(200))
        let boundAt = Self.iso8601(Date())
        let pid = Int(getpid())
        timer.setEventHandler {
            write(pid: pid, port: port, boundAt: boundAt, hostBox: hostBox)
        }
        timer.resume()
        // Keep a strong reference so the source is not deallocated.
        TimerBox.shared.timer = timer
    }

    private static func write(pid: Int, port: UInt16, boundAt: String, hostBox: HostBox) {
        let stateDir = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(ClawixPathSurface.bridgeStateDirectory, isDirectory: true)
        try? FileManager.default.createDirectory(at: stateDir, withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700])
        let target = stateDir.appendingPathComponent(ClawixPathSurface.bridgeStatusFile)
        let tmp = stateDir.appendingPathComponent(ClawixPathSurface.bridgeStatusTempFile)

        // Reading host state requires hopping to MainActor. Doing it
        // inline from the timer's utility queue would deadlock if the
        // main actor is busy, so we dispatch and let the next tick
        // catch up if we miss this one.
        DispatchQueue.main.async {
            let snap = hostBox.snapshot()
            var payload: [String: Any] = [
                "version": "0.1.2",
                "pid": pid,
                "port": Int(port),
                "boundAt": boundAt,
                "lastHeartbeatAt": iso8601(Date()),
                "peerCount": BridgeStats.shared.activeSessionCount,
                "state": snap.state,
                "chatCount": snap.chatCount,
                "lastError": snap.errorMessage as Any? ?? NSNull(),
                "lastErrorMessage": snap.errorMessage as Any? ?? NSNull()
            ]
            if let lastSync = snap.lastSyncAt {
                payload["lastSyncAt"] = iso8601(lastSync)
            } else {
                payload["lastSyncAt"] = NSNull()
            }
            guard let data = try? JSONSerialization.data(withJSONObject: payload, options: [.sortedKeys, .prettyPrinted]) else { return }
            do {
                try data.write(to: tmp, options: .atomic)
                try? FileManager.default.removeItem(at: target)
                try FileManager.default.moveItem(at: tmp, to: target)
            } catch {
                BridgeLog.write("heartbeat write failed: \(error)")
            }
        }
    }

    private static let isoFormatter: ISO8601DateFormatter = {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return f
    }()

    private static func iso8601(_ date: Date) -> String { isoFormatter.string(from: date) }
}

final class TimerBox: @unchecked Sendable {
    static let shared = TimerBox()
    var timer: DispatchSourceTimer?
}

enum BridgeLog {
    static func write(_ message: String) {
        let safe = redact(message)
        FileHandle.standardError.write(Data(("[clawix-bridge] \(safe)\n").utf8))
    }

    private static func redact(_ s: String) -> String {
        let patterns = [
            "(?<![A-Za-z0-9_-])[A-Za-z0-9_-]{32,}(?![A-Za-z0-9_-])",
            NSHomeDirectory().replacingOccurrences(of: "/", with: "\\/")
        ]
        return patterns.reduce(s) { current, pattern in
            guard let re = try? NSRegularExpression(pattern: pattern) else { return current }
            let range = NSRange(current.startIndex..., in: current)
            let replacement = pattern.hasPrefix("(?<!") ? "<redacted>" : "~"
            return re.stringByReplacingMatches(in: current, range: range, withTemplate: replacement)
        }
    }
}

struct BackendBinary {
    let path: URL

    static func resolve(environment: [String: String]) -> BackendBinary? {
        if let override = environment[ClawixEnv.bridgeBackendPath], !override.isEmpty {
            let url = URL(fileURLWithPath: (override as NSString).expandingTildeInPath)
            if FileManager.default.isExecutableFile(atPath: url.path) {
                return BackendBinary(path: url)
            }
        }
        for candidate in candidatePaths() where FileManager.default.isExecutableFile(atPath: candidate.path) {
            return BackendBinary(path: candidate)
        }
        return nil
    }

    private static func candidatePaths() -> [URL] {
        var out: [URL] = []
        if let manual = UserDefaults.standard.string(forKey: ClawixDefaultsSurface.binaryPath), !manual.isEmpty {
            out.append(URL(fileURLWithPath: manual))
        }
        out.append(URL(fileURLWithPath: "/Applications/Codex.app/Contents/Resources/codex"))
        let nvmRoot = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".nvm/versions/node", isDirectory: true)
        if let versions = try? FileManager.default.contentsOfDirectory(at: nvmRoot, includingPropertiesForKeys: nil) {
            for version in versions.sorted(by: { $0.lastPathComponent > $1.lastPathComponent }) {
                out.append(version.appendingPathComponent("bin/codex"))
            }
        }
        out.append(URL(fileURLWithPath: "/opt/homebrew/bin/codex"))
        out.append(URL(fileURLWithPath: "/usr/local/bin/codex"))
        out.append(URL(fileURLWithPath: "/usr/bin/codex"))
        return out
    }
}

@MainActor
final class DaemonEngineHost: EngineHost {
    private let backend: BackendClient
    private let pairing: PairingService
    private let chatsSubject = CurrentValueSubject<[BridgeChatSnapshot], Never>([])
    private let stateSubject = CurrentValueSubject<BridgeRuntimeState, Never>(.booting)
    /// Mirrors what the GUI's `ClawixService.refreshRateLimits` puts on
    /// `appState.rateLimits` + `rateLimitsByLimitId` when no daemon is
    /// involved. Seeded from `account/rateLimits/read` once at boot
    /// and refreshed every time Codex emits `account/rateLimits/updated`.
    /// Desktop sessions that connect mid-session pull the cached value
    /// via `requestRateLimits`; the bus also pushes a `rateLimitsUpdated`
    /// frame on each new payload for already-connected sessions.
    private let rateLimitsSubject = CurrentValueSubject<WireRateLimitsPayload, Never>(.empty)
    private let initialRequestTimeoutSeconds: TimeInterval
    private let threadListTimeoutSeconds: TimeInterval
    private let rateLimitsTimeoutSeconds: TimeInterval
    /// Last `lastSyncAt` we recorded, exposed to the heartbeat so the
    /// CLI can show "synced 5s ago". Updated every time we publish a
    /// non-empty chats list; not bumped for empty placeholders.
    private(set) var lastChatsPublishedAt: Date?
    private var chatByThread: [String: String] = [:]
    private var threadByChat: [String: String] = [:]
    private var activeAssistantIdByThread: [String: String] = [:]
    private var activeTurnByThread: [String: String] = [:]
    private let meshStore = RemoteMeshStore()
    private var remoteJobByThread: [String: String] = [:]

    init(binary: BackendBinary, pairing: PairingService) {
        self.backend = BackendClient(binary: binary)
        self.pairing = pairing
        let env = ProcessInfo.processInfo.environment
        self.initialRequestTimeoutSeconds = Self.timeout(from: env["CLAWIX_BRIDGE_INITIAL_TIMEOUT_SECONDS"], default: 12)
        self.threadListTimeoutSeconds = Self.timeout(from: env["CLAWIX_BRIDGE_THREAD_LIST_TIMEOUT_SECONDS"], default: 10)
        self.rateLimitsTimeoutSeconds = Self.timeout(from: env["CLAWIX_BRIDGE_RATE_LIMITS_TIMEOUT_SECONDS"], default: 4)
    }

    private static func timeout(from raw: String?, default fallback: TimeInterval) -> TimeInterval {
        guard let raw, let value = TimeInterval(raw), value > 0 else { return fallback }
        return value
    }

    var bridgeChatsCurrent: [BridgeChatSnapshot] { chatsSubject.value }
    var bridgeChatsPublisher: AnyPublisher<[BridgeChatSnapshot], Never> {
        chatsSubject.eraseToAnyPublisher()
    }

    var bridgeStateCurrent: BridgeRuntimeState { stateSubject.value }
    var bridgeStatePublisher: AnyPublisher<BridgeRuntimeState, Never> {
        stateSubject.eraseToAnyPublisher()
    }

    var bridgeRateLimitsCurrent: WireRateLimitsPayload { rateLimitsSubject.value }
    var bridgeRateLimitsPublisher: AnyPublisher<WireRateLimitsPayload, Never> {
        rateLimitsSubject.eraseToAnyPublisher()
    }

    func bootstrap() async {
        BridgeLog.write("bootstrap-start")
        stateSubject.send(.syncing)
        do {
            try await backend.start()
            startEvents()
            _ = try await backend.send(
                method: "initialize",
                params: InitializeParams(
                    clientInfo: InitializeClientIdentity(name: "Clawix Bridge", title: "Clawix", version: "1"),
                    capabilities: InitializeCapabilities(extensionFields: true, optOutNotificationMethods: nil)
                ),
                timeoutSeconds: initialRequestTimeoutSeconds
            )
            try await backend.notify(method: "initialized", params: EmptyObject())
            BridgeLog.write("backend-initialized")
            let didLoadThreads = await reloadThreads()
            await refreshRateLimits()
            if didLoadThreads {
                stateSubject.send(.ready)
            }
        } catch {
            BridgeLog.write("bootstrap failed \(error)")
            stateSubject.send(.error(shortReason(error)))
        }
    }

    /// One-shot pull of `account/rateLimits/read` after the backend
    /// finishes `initialize`. The snapshot lands on `rateLimitsSubject`
    /// so any desktop session that already sent `requestRateLimits`
    /// gets the freshest data via the bus's emit, and any session that
    /// connects afterwards reads the cached value synchronously.
    /// Failures are non-fatal: we leave the subject empty so the GUI
    /// just hides the widget instead of showing stale data.
    private func refreshRateLimits() async {
        do {
            let response = try await backend.send(
                method: "account/rateLimits/read",
                params: EmptyObject(),
                expecting: DaemonGetAccountRateLimitsResponse.self,
                timeoutSeconds: rateLimitsTimeoutSeconds
            )
            rateLimitsSubject.send(WireRateLimitsPayload(
                snapshot: wireSnapshot(from: response.rateLimits),
                byLimitId: wireByLimitId(from: response.rateLimitsByLimitId)
            ))
            BridgeLog.write("rate-limits-read ok buckets=\(response.rateLimitsByLimitId?.count ?? 0)")
        } catch {
            BridgeLog.write("rate-limits-read failed \(error)")
        }
    }

    private func wireSnapshot(from raw: DaemonRateLimitSnapshot) -> WireRateLimitSnapshot {
        WireRateLimitSnapshot(
            primary: raw.primary.map { WireRateLimitWindow(
                usedPercent: $0.usedPercent,
                resetsAt: $0.resetsAt,
                windowDurationMins: $0.windowDurationMins
            )},
            secondary: raw.secondary.map { WireRateLimitWindow(
                usedPercent: $0.usedPercent,
                resetsAt: $0.resetsAt,
                windowDurationMins: $0.windowDurationMins
            )},
            credits: raw.credits.map { WireCreditsSnapshot(
                hasCredits: $0.hasCredits,
                unlimited: $0.unlimited,
                balance: $0.balance
            )},
            limitId: raw.limitId,
            limitName: raw.limitName
        )
    }

    private func wireByLimitId(from raw: [String: DaemonRateLimitSnapshot]?) -> [String: WireRateLimitSnapshot] {
        guard let raw else { return [:] }
        var out: [String: WireRateLimitSnapshot] = [:]
        for (key, value) in raw {
            out[key] = wireSnapshot(from: value)
        }
        return out
    }

    /// Compress an arbitrary `Error` into a short single-line string for
    /// the `bridgeState(.error)` payload. The underlying `localizedDescription`
    /// can be multi-line on Codex backend errors; the iPhone error card
    /// only has room for one short sentence.
    private func shortReason(_ error: Error) -> String {
        let raw = "\(error)"
        let trimmed = raw.replacingOccurrences(of: "\n", with: " ")
        return String(trimmed.prefix(160))
    }

    func handleHydrateHistory(sessionId: UUID) {
        hydrate(chatId: sessionId.uuidString)
    }

    func handleSendMessage(sessionId: UUID, text: String, attachments: [WireAttachment]) {
        let chatIdString = sessionId.uuidString
        // Split image vs audio attachments. Images go to Codex as
        // `localImage` items; audio is transcribed via Whisper, stored
        // for future replay, and the transcript becomes (or augments)
        // the prompt text the model sees. Order is preserved within
        // each kind, which is enough since the iPhone composer never
        // mixes images with audio in the same send today.
        let imageAttachments = attachments.filter { $0.kind == .image }
        let audioAttachments = attachments.filter { $0.kind == .audio }
        Task { @MainActor in
            do {
                let threadId = try await ensureThread(chatId: chatIdString, firstPrompt: text)
                let imagePaths = AttachmentSpooler.write(
                    attachments: imageAttachments,
                    scope: threadId,
                    log: { BridgeLog.write($0) }
                )
                // Transcribe + persist each audio attachment in order.
                // The user message ID is minted up-front so the audio
                // store entry can carry it (helps the GUI's own
                // hydrate path attach the bubble back without having
                // to re-match by content).
                let userMessageId = UUID().uuidString
                let audioRef = try await ingestAudioAttachments(
                    audioAttachments,
                    threadId: threadId,
                    chatId: chatIdString,
                    messageId: userMessageId,
                    providedTranscript: text
                )
                // Audio's transcript replaces the text input when the
                // user sent only a voice clip (the iPhone composer
                // sends `text == transcript` already, but defending
                // against an empty `text` field is cheap and lets the
                // shape stay simple for future surfaces that ship an
                // audio-only prompt).
                let promptText: String = {
                    if !text.isEmpty { return text }
                    if let audioRef, !audioRef.transcript.isEmpty { return audioRef.transcript }
                    return text
                }()
                let preview = userMessagePreview(
                    text: promptText,
                    imageCount: imagePaths.count,
                    hasAudio: audioRef != nil
                )
                appendMessage(chatId: chatIdString, message: WireMessage(
                    id: userMessageId,
                    role: .user,
                    content: preview,
                    streamingFinished: true,
                    timestamp: Date(),
                    audioRef: audioRef?.ref,
                    attachments: imageAttachments
                ))
                updateChat(chatId: chatIdString) { chat in
                    chat.hasActiveTurn = true
                    chat.lastTurnInterrupted = false
                    chat.lastMessageAt = Date()
                    chat.lastMessagePreview = String(preview.prefix(140))
                }
                var input: [TurnStartUserInput] = []
                if !promptText.isEmpty { input.append(.text(promptText)) }
                for path in imagePaths { input.append(.localImage(path: path)) }
                if input.isEmpty { input.append(.text(promptText)) }
                let result = try await backend.send(
                    method: "turn/start",
                    params: TurnStartParams(
                        threadId: threadId,
                        input: input,
                        model: nil,
                        effort: nil,
                        serviceTier: nil,
                        collaborationMode: nil
                    ),
                    expecting: TurnStartResult.self
                )
                activeTurnByThread[threadId] = result.turn.id
            } catch {
                appendError(chatId: chatIdString, message: "\(error)")
            }
        }
    }

    private func userMessagePreview(text: String, imageCount: Int, hasAudio: Bool = false) -> String {
        // The chat row preview shows the same text Codex actually
        // received as the prompt; if there are images the count gets
        // inlined the way the macOS composer already does. Audio
        // messages don't add a tag because the transcript already is
        // the visible content and surfaces (chat row, timeline) read
        // cleaner without a "[voice]" prefix muddying user prompts.
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard imageCount > 0 else {
            return hasAudio && trimmed.isEmpty ? "[voice]" : text
        }
        let label = imageCount == 1 ? "[image]" : "[\(imageCount) images]"
        return trimmed.isEmpty ? label : "\(label) \(text)"
    }

    func handleNewSession(sessionId: UUID, text: String, attachments: [WireAttachment]) {
        // The iPhone composer treats the first prompt of a chat as a
        // `newSession` frame so the daemon can mint the thread with the
        // chat's pre-allocated UUID. The actual run path is identical
        // to a regular send: ensureThread creates the thread on demand.
        handleSendMessage(sessionId: sessionId, text: text, attachments: attachments)
    }

    func handleRequestAudio(
        audioId: String,
        reply: @MainActor @escaping (String?, String?, String?) -> Void
    ) {
        // The bridge thread posts this; jump back to MainActor for the
        // reply send so the session.send path stays single-actor like
        // the other handlers.
        Task { @MainActor in
            if let client = self.audioCatalogClient {
                do {
                    let result = try await client.getBytes(audioId: audioId, appId: "clawix")
                    reply(result.base64, result.mimeType, nil)
                    return
                } catch ClawJSAudioClient.Error.notFound {
                    reply(nil, nil, "Audio no longer available")
                    return
                } catch {
                    reply(nil, nil, error.localizedDescription)
                    return
                }
            }
            reply(nil, nil, "Audio catalog is not available")
        }
    }

    /// Lazy view of the audio catalog client. Resolves to non-nil when
    /// the supervisor (whichever process spawned it: GUI or, in the
    /// future, the daemon itself) has written its per-session bearer
    /// token to the canonical data-dir path. Cached after first hit so
    /// the hot path doesn't re-read the file on every replay.
    private var cachedAudioCatalogClient: ClawJSAudioClient?
    private var didProbeAudioCatalog = false
    var audioCatalogClient: ClawJSAudioClient? {
        if didProbeAudioCatalog { return cachedAudioCatalogClient }
        didProbeAudioCatalog = true
        let tokenDir = Self.audioCatalogTokenDir
        guard let token = ClawJSAudioClient.tokenFromAdminTokenFile(tokenDir) else {
            return nil
        }
        cachedAudioCatalogClient = ClawJSAudioClient(bearerToken: token)
        return cachedAudioCatalogClient
    }

    /// Mirrors `ClawJSServiceManager.dataDirectoryURL(for: .audio)`
    /// path resolution. The supervisor (GUI) writes the per-session
    /// bearer token to `<root>/.admin-token` here on every spawn; the
    /// daemon helper reads it lazily because the manager lives in a
    /// different process.
    private static var audioCatalogTokenDir: URL {
        let env = ProcessInfo.processInfo.environment
        let root: URL
        if env[ClawixEnv.dummyMode] == "1", let custom = env[ClawixEnv.backendHome], !custom.isEmpty {
            root = URL(fileURLWithPath: custom, isDirectory: true)
        } else {
            root = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
                .appendingPathComponent(ClawixPathSurface.embeddedClawJS, isDirectory: true)
        }
        return root
            .appendingPathComponent(ClawixPathSurface.workspace, isDirectory: true)
            .appendingPathComponent(ClawixPathSurface.clawWorkspace, isDirectory: true)
            .appendingPathComponent(ClawixPathSurface.audio, isDirectory: true)
    }

    func handleTranscribeAudio(
        requestId: String,
        audioBase64: String,
        mimeType: String,
        language: String?,
        reply: @MainActor @escaping (String, String?) -> Void
    ) {
        #if canImport(WhisperKit)
        // Audio blobs from the iPhone arrive base64-encoded inside the
        // bridge frame because the WebSocket transport is text-only.
        // Spool to a per-request file in the same /tmp tree the image
        // attachment path uses, then hand the file to WhisperKit.
        let suiteName = ClawixEnv.value(ClawixEnv.bridgeDefaultsSuite)
        let defaults = suiteName.flatMap { UserDefaults(suiteName: $0) } ?? .standard
        let activeRaw = defaults.string(forKey: DictationModelManager.activeModelDefaultsKey) ?? ""
        let model = DictationModel(rawValue: activeRaw) ?? .default

        Task { @MainActor in
            let ext = audioExtension(mimeType: mimeType)
            let root = URL(fileURLWithPath: NSTemporaryDirectory())
                .appendingPathComponent("clawix-attachments", isDirectory: true)
                .appendingPathComponent("dictation", isDirectory: true)
            let url = root.appendingPathComponent("\(requestId).\(ext)")
            do {
                try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
                guard let data = Data(base64Encoded: audioBase64) else {
                    reply("", "Audio decode failed")
                    return
                }
                try data.write(to: url, options: .atomic)
                let text = try await TranscriptionService.shared.transcribe(
                    fileURL: url,
                    using: model,
                    language: language
                )
                reply(text, nil)
            } catch {
                reply("", error.localizedDescription)
            }
        }
        #else
        // Linux build: WhisperKit is unavailable. The Tauri shell handles
        // dictation locally via whisper.cpp; remote dictation requests
        // from iPhone clients are answered with an unavailable error
        // until the Linux daemon ships its own whisper.cpp wrapper.
        reply("", "Server-side transcription is not available on this host")
        #endif
    }

    func handleInterruptTurn(sessionId: UUID) {
        let chatIdString = sessionId.uuidString
        guard let threadId = threadByChat[chatIdString],
              let turnId = activeTurnByThread[threadId]
        else { return }
        // Clear UI-side state first so the iPhone shimmer disappears the
        // moment the frame round-trips back. The backend cancel is
        // fire-and-forget; any deltas already in flight for this turn
        // are gated by `activeTurnByThread`/`activeAssistantIdByThread`.
        activeTurnByThread[threadId] = nil
        if let assistantId = activeAssistantIdByThread[threadId] {
            // Mirror the macOS behaviour: if the assistant placeholder
            // is still empty (no streamed content), drop it; otherwise
            // freeze it as finished so the partial answer stays.
            let messages = existingMessages(chatId: chatIdString)
            if let msg = messages.first(where: { $0.id == assistantId }),
               msg.content.isEmpty && msg.reasoningText.isEmpty {
                updateSnapshot(chatId: chatIdString) { snap in
                    snap.messages.removeAll { $0.id == assistantId }
                }
            } else {
                updateMessage(chatId: chatIdString, messageId: assistantId) {
                    $0.streamingFinished = true
                }
            }
            activeAssistantIdByThread[threadId] = nil
        }
        updateChat(chatId: chatIdString) {
            $0.hasActiveTurn = false
            $0.lastTurnInterrupted = true
        }
        Task { @MainActor in
            do {
                _ = try await backend.send(
                    method: "turn/interrupt",
                    params: TurnInterruptParams(threadId: threadId, turnId: turnId),
                    expecting: EmptyResponse.self
                )
            } catch {
                BridgeLog.write("turn/interrupt failed \(error)")
            }
        }
    }

    func handleArchiveSession(sessionId: UUID, archived: Bool) {
        let chatIdString = sessionId.uuidString
        guard let threadId = threadByChat[chatIdString] else { return }
        Task { @MainActor in
            do {
                if archived {
                    _ = try await backend.send(
                        method: "thread/archive",
                        params: ThreadArchiveParams(threadId: threadId),
                        expecting: EmptyResponse.self
                    )
                } else {
                    _ = try await backend.send(
                        method: "thread/unarchive",
                        params: ThreadUnarchiveParams(threadId: threadId),
                        expecting: EmptyResponse.self
                    )
                }
                updateChat(chatId: chatIdString) {
                    $0.isArchived = archived
                    if archived { $0.isPinned = false }
                }
            } catch {
                appendError(chatId: chatIdString, message: "\(error)")
            }
        }
    }

    func handleRenameSession(sessionId: UUID, title: String) {
        let trimmed = title.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        let chatIdString = sessionId.uuidString
        guard let threadId = threadByChat[chatIdString] else { return }
        // Optimistic local update so any client subscribed to this
        // session sees the new title before the runtime ack lands. The
        // bus will republish via `sessionUpdated`, which all peers (the
        // initiating iPhone included) treat as the canonical state.
        updateChat(chatId: chatIdString) {
            $0.title = trimmed
        }
        Task { @MainActor in
            do {
                _ = try await backend.send(
                    method: "thread/name/set",
                    params: ThreadSetNameParams(threadId: threadId, name: trimmed),
                    expecting: EmptyResponse.self
                )
            } catch {
                appendError(chatId: chatIdString, message: "\(error)")
            }
        }
    }

    func handlePairingStart() -> (qrJson: String, bearer: String)? {
        return (pairing.qrPayload(), pairing.bearer)
    }

    func startRemoteJob(
        jobId: String,
        requesterNodeId: String,
        workspacePath: String,
        prompt: String
    ) async throws -> RemoteJob {
        let workspace = URL(fileURLWithPath: workspacePath).standardizedFileURL.path
        guard meshStore.allowsWorkspace(workspace) else {
            throw RemoteMeshError.workspaceDenied
        }
        let chatId = UUID().uuidString
        var job = RemoteJob(
            id: jobId,
            requesterNodeId: requesterNodeId,
            workspacePath: workspace,
            prompt: prompt,
            status: .running,
            remoteChatId: chatId
        )
        meshStore.upsert(job: job)
        meshStore.append(event: RemoteJobEvent(jobId: jobId, type: "accepted", message: "Remote job accepted"))

        do {
            let result = try await backend.send(
                method: "thread/start",
                params: ThreadStartParams(
                    cwd: workspace,
                    model: nil,
                    approvalPolicy: nil,
                    sandbox: nil,
                    personalizationPreset: nil,
                    serviceTier: nil,
                    collaborationMode: nil
                ),
                expecting: ThreadStartResult.self
            )
            let threadId = result.thread.id
            chatByThread[threadId] = chatId
            threadByChat[chatId] = threadId
            remoteJobByThread[threadId] = jobId
            job.remoteThreadId = threadId
            job.updatedAt = Date()
            meshStore.upsert(job: job)
            ensureSnapshot(chatId: chatId, firstPrompt: prompt, cwd: workspace)
            appendMessage(chatId: chatId, message: WireMessage(
                id: UUID().uuidString,
                role: .user,
                content: prompt,
                streamingFinished: true,
                timestamp: Date()
            ))
            updateChat(chatId: chatId) {
                $0.hasActiveTurn = true
                $0.lastMessagePreview = String(prompt.prefix(140))
                $0.lastMessageAt = Date()
                $0.threadId = threadId
            }
            meshStore.append(event: RemoteJobEvent(jobId: jobId, type: "threadStarted", message: threadId))
            let turn = try await backend.send(
                method: "turn/start",
                params: TurnStartParams(
                    threadId: threadId,
                    input: [.text(prompt)],
                    model: nil,
                    effort: nil,
                    serviceTier: nil,
                    collaborationMode: nil
                ),
                expecting: TurnStartResult.self
            )
            activeTurnByThread[threadId] = turn.turn.id
            meshStore.append(event: RemoteJobEvent(jobId: jobId, type: "turnStarted", message: turn.turn.id))
            job.updatedAt = Date()
            meshStore.upsert(job: job)
            return job
        } catch {
            job.status = .failed
            job.errorMessage = "\(error)"
            job.updatedAt = Date()
            meshStore.upsert(job: job)
            meshStore.append(event: RemoteJobEvent(jobId: jobId, type: "failed", message: "\(error)"))
            throw error
        }
    }

    func cancelRemoteJob(jobId: String) async {
        guard var job = meshStore.job(id: jobId) else { return }
        if let threadId = job.remoteThreadId,
           let chatId = chatByThread[threadId],
           let turnId = activeTurnByThread[threadId] {
            activeTurnByThread[threadId] = nil
            do {
                _ = try await backend.send(
                    method: "turn/interrupt",
                    params: TurnInterruptParams(threadId: threadId, turnId: turnId),
                    expecting: EmptyResponse.self
                )
            } catch {
                BridgeLog.write("mesh job cancel failed \(error)")
            }
            updateChat(chatId: chatId) {
                $0.hasActiveTurn = false
                $0.lastTurnInterrupted = true
            }
        }
        job.status = .cancelled
        job.updatedAt = Date()
        meshStore.upsert(job: job)
        meshStore.append(event: RemoteJobEvent(jobId: jobId, type: "cancelled", message: "Remote job cancelled"))
    }

    private func reloadThreads() async -> Bool {
        do {
            let pageSize = 160
            let maxPages = 10
            var collected: [AgentThreadSummary] = []
            var seenIds = Set<String>()
            var cursor: String? = nil
            var page = 0

            repeat {
                let response = try await backend.send(
                    method: "thread/list",
                    params: ThreadListParams(
                        archived: false,
                        cursor: cursor,
                        cwd: nil,
                        limit: pageSize,
                        modelProviders: nil,
                        searchTerm: nil,
                        sortDirection: "desc",
                        sortKey: "updated_at",
                        sourceKinds: nil,
                        useStateDbOnly: nil
                    ),
                    expecting: ThreadListResponse.self,
                    timeoutSeconds: threadListTimeoutSeconds
                )
                for thread in response.data where seenIds.insert(thread.id).inserted {
                    collected.append(thread)
                }
                cursor = response.nextCursor
                page += 1
            } while cursor != nil && page < maxPages

            let runtimeSnapshots = collected.map(snapshot(from:))
            BridgeLog.write("thread-list ok count=\(runtimeSnapshots.count) source=runtime pages=\(page)")
            chatsSubject.send(runtimeSnapshots)
            lastChatsPublishedAt = Date()
            return true
        } catch {
            BridgeLog.write("thread-list failed \(error)")
            // Surface to peers as an error state rather than silently
            // leaving them on `syncing` forever. The bootstrap caller
            // will move us to `.ready` only on success, so on failure
            // the iPhone sees an actionable message instead of a
            // perpetual spinner.
            stateSubject.send(.error("Couldn't load chats: \(shortReason(error))"))
            return false
        }
    }

    private func title(fromFirstUserMessage message: String?, fallback: String) -> String {
        let trimmed = (message ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmed.isEmpty {
            let firstLine = trimmed.split(separator: "\n", maxSplits: 1, omittingEmptySubsequences: true).first
            return String((firstLine.map(String.init) ?? trimmed).prefix(80))
        }
        return fallback
    }

    private func snapshot(from thread: AgentThreadSummary) -> BridgeChatSnapshot {
        let chatId = chatByThread[thread.id] ?? UUID().uuidString
        chatByThread[thread.id] = chatId
        threadByChat[chatId] = thread.id
        let archived = thread.archived ?? false
        return BridgeChatSnapshot(
            chat: WireSession(
                id: chatId,
                title: title(for: thread),
                createdAt: thread.updatedDate,
                isPinned: false,
                isArchived: archived,
                hasActiveTurn: activeTurnByThread[thread.id] != nil,
                lastMessageAt: thread.updatedDate,
                lastMessagePreview: thread.preview,
                cwd: thread.cwd,
                threadId: thread.id
            ),
            messages: existingMessages(chatId: chatId)
        )
    }

    private func title(for thread: AgentThreadSummary) -> String {
        if let name = thread.name?.trimmingCharacters(in: .whitespacesAndNewlines), !name.isEmpty {
            return name
        }
        let preview = thread.preview.trimmingCharacters(in: .whitespacesAndNewlines)
        return preview.isEmpty ? "Conversation" : String(preview.prefix(60))
    }

    private func ensureThread(chatId: String, firstPrompt: String) async throws -> String {
        if let threadId = threadByChat[chatId] {
            return threadId
        }
        let result = try await backend.send(
            method: "thread/start",
            params: ThreadStartParams(
                cwd: FileManager.default.homeDirectoryForCurrentUser.path,
                model: nil,
                approvalPolicy: nil,
                sandbox: nil,
                personalizationPreset: nil,
                serviceTier: nil,
                collaborationMode: nil
            ),
            expecting: ThreadStartResult.self
        )
        let threadId = result.thread.id
        chatByThread[threadId] = chatId
        threadByChat[chatId] = threadId
        ensureSnapshot(chatId: chatId, firstPrompt: firstPrompt, cwd: result.thread.cwd)
        updateSnapshot(chatId: chatId) { snap in
            let trimmed = firstPrompt.trimmingCharacters(in: .whitespacesAndNewlines)
            snap.chat.title = trimmed.isEmpty ? "Conversation" : String(trimmed.prefix(60))
            snap.chat.cwd = result.thread.cwd
            // Stamp the freshly minted Codex thread id onto the wire
            // chat so desktop clients can reconcile pin / project
            // metadata against `BackendStateReader` going forward.
            snap.chat.threadId = threadId
        }
        return threadId
    }

    private func ensureSnapshot(chatId: String, firstPrompt: String, cwd: String?) {
        guard !bridgeChatsCurrent.contains(where: { $0.id == chatId }) else { return }
        let trimmed = firstPrompt.trimmingCharacters(in: .whitespacesAndNewlines)
        var snapshots = bridgeChatsCurrent
        snapshots.insert(
            BridgeChatSnapshot(
                chat: WireSession(
                    id: chatId,
                    title: trimmed.isEmpty ? "Conversation" : String(trimmed.prefix(60)),
                    createdAt: Date(),
                    isArchived: false,
                    hasActiveTurn: false,
                    lastMessageAt: Date(),
                    lastMessagePreview: String(trimmed.prefix(140)),
                    cwd: cwd
                ),
                messages: []
            ),
            at: 0
        )
        chatsSubject.send(snapshots)
    }

    private func hydrate(chatId: String) {
        _ = chatId
    }

    private func startEvents() {
        let stream = backend.events
        Task { @MainActor in
            for await event in stream {
                handle(event)
            }
        }
    }

    private func handle(_ event: BackendEvent) {
        switch event {
        case let .request(id, method, _):
            if method == "item/tool/requestUserInput" {
                try? backend.resolve(id: id, result: ToolRequestUserInputResponse(answers: [:]))
            }
        case let .notification(method, params):
            handleNotification(method: method, params: params)
        }
    }

    private func handleNotification(method: String, params: JSONValue?) {
        switch method {
        case "turn/started":
            guard let payload = try? params?.decode(TurnEnvelope.self),
                  let chatId = chatByThread[payload.threadId]
            else { return }
            activeTurnByThread[payload.threadId] = payload.turn.id
            let assistantId = ensureAssistant(chatId: chatId, threadId: payload.threadId)
            // Stamp the live "Worked for Xs" counter on the placeholder so
            // the chat row's header ticks live while the model is working.
            // `endedAt` stays nil; `turn/completed` freezes it.
            let started = Date()
            updateMessage(chatId: chatId, messageId: assistantId) { msg in
                if msg.workSummary == nil {
                    msg.workSummary = WireWorkSummary(
                        startedAt: started,
                        endedAt: nil,
                        items: []
                    )
                }
            }
            updateChat(chatId: chatId) { $0.hasActiveTurn = true }
        case "item/agentMessage/delta":
            guard let payload = try? params?.decode(AgentMessageDelta.self),
                  let chatId = chatByThread[payload.threadId]
            else { return }
            if let jobId = remoteJobByThread[payload.threadId] {
                if var job = meshStore.job(id: jobId) {
                    job.resultText = (job.resultText ?? "") + payload.delta
                    job.updatedAt = Date()
                    meshStore.upsert(job: job)
                }
                meshStore.append(event: RemoteJobEvent(jobId: jobId, type: "delta", message: payload.delta))
            }
            let assistantId = ensureAssistant(chatId: chatId, threadId: payload.threadId)
            updateMessage(chatId: chatId, messageId: assistantId) { msg in
                msg.content += payload.delta
                msg.streamingFinished = false
            }
        case "item/reasoning/textDelta", "item/reasoning/summaryTextDelta":
            guard let payload = try? params?.decode(ReasoningTextDelta.self),
                  let chatId = chatByThread[payload.threadId]
            else { return }
            let assistantId = ensureAssistant(chatId: chatId, threadId: payload.threadId)
            updateMessage(chatId: chatId, messageId: assistantId) { msg in
                msg.reasoningText += payload.delta
                msg.streamingFinished = false
            }
        case "item/completed":
            guard let payload = try? params?.decode(ItemEnvelope.self),
                  payload.item.type == "agentMessage",
                  let chatId = chatByThread[payload.threadId],
                  let assistantId = activeAssistantIdByThread[payload.threadId]
            else { return }
            updateMessage(chatId: chatId, messageId: assistantId) { msg in
                if let text = payload.item.text, !text.isEmpty {
                    msg.content = text
                }
                msg.streamingFinished = true
            }
        case "turn/completed":
            guard let payload = try? params?.decode(TurnEnvelope.self),
                  let chatId = chatByThread[payload.threadId]
            else { return }
            // Freeze the work-summary counter at turn close so the live
            // ticker stops; without this the chat row keeps incrementing
            // even though the agent is done.
            if let assistantId = activeAssistantIdByThread[payload.threadId] {
                let ended = Date()
                updateMessage(chatId: chatId, messageId: assistantId) { msg in
                    if msg.workSummary != nil, msg.workSummary?.endedAt == nil {
                        msg.workSummary?.endedAt = ended
                    }
                }
            }
            activeTurnByThread[payload.threadId] = nil
            activeAssistantIdByThread[payload.threadId] = nil
            updateChat(chatId: chatId) {
                $0.hasActiveTurn = false
                $0.lastTurnInterrupted = false
            }
            if let jobId = remoteJobByThread[payload.threadId] {
                var job = meshStore.job(id: jobId) ?? RemoteJob(
                    id: jobId,
                    requesterNodeId: "",
                    workspacePath: "",
                    prompt: ""
                )
                job.status = .completed
                if job.resultText == nil || job.resultText?.isEmpty == true {
                    job.resultText = existingMessages(chatId: chatId).last(where: { $0.role == .assistant })?.content
                }
                job.updatedAt = Date()
                meshStore.upsert(job: job)
                meshStore.append(event: RemoteJobEvent(jobId: jobId, type: "completed", message: job.resultText ?? ""))
                remoteJobByThread[payload.threadId] = nil
            }
        case "account/rateLimits/updated":
            guard let payload = try? params?.decode(DaemonAccountRateLimitsUpdatedNotification.self) else { return }
            rateLimitsSubject.send(WireRateLimitsPayload(
                snapshot: wireSnapshot(from: payload.rateLimits),
                byLimitId: wireByLimitId(from: payload.rateLimitsByLimitId)
            ))
        default:
            break
        }
    }

    @discardableResult
    private func ensureAssistant(chatId: String, threadId: String) -> String {
        if let id = activeAssistantIdByThread[threadId] { return id }
        let id = UUID().uuidString
        activeAssistantIdByThread[threadId] = id
        appendMessage(chatId: chatId, message: WireMessage(
            id: id,
            role: .assistant,
            content: "",
            streamingFinished: false,
            timestamp: Date()
        ))
        return id
    }

    private func appendError(chatId: String, message: String) {
        appendMessage(chatId: chatId, message: WireMessage(
            id: UUID().uuidString,
            role: .assistant,
            content: message,
            streamingFinished: true,
            isError: true,
            timestamp: Date()
        ))
        updateChat(chatId: chatId) { $0.hasActiveTurn = false }
    }

    private func existingMessages(chatId: String) -> [WireMessage] {
        bridgeChatsCurrent.first(where: { $0.id == chatId })?.messages ?? []
    }

    private func appendMessage(chatId: String, message: WireMessage) {
        updateSnapshot(chatId: chatId) { snap in
            snap.messages.append(message)
            snap.chat.lastMessageAt = message.timestamp
            snap.chat.lastMessagePreview = String(message.content.prefix(140))
        }
    }

    private func updateMessage(chatId: String, messageId: String, mutate: (inout WireMessage) -> Void) {
        updateSnapshot(chatId: chatId) { snap in
            guard let idx = snap.messages.firstIndex(where: { $0.id == messageId }) else { return }
            mutate(&snap.messages[idx])
            let msg = snap.messages[idx]
            snap.chat.lastMessageAt = msg.timestamp
            snap.chat.lastMessagePreview = String(msg.content.prefix(140))
        }
    }

    private func updateChat(chatId: String, mutate: (inout WireSession) -> Void) {
        updateSnapshot(chatId: chatId) { mutate(&$0.chat) }
    }

    private func updateSnapshot(chatId: String, mutate: (inout MutableSnapshot) -> Void) {
        var snapshots = bridgeChatsCurrent
        guard let index = snapshots.firstIndex(where: { $0.id == chatId }) else { return }
        var mutable = MutableSnapshot(snapshots[index])
        mutate(&mutable)
        snapshots[index] = mutable.snapshot
        chatsSubject.send(snapshots)
    }
}

private func preserveUserAttachments(existing: [WireMessage], incoming: [WireMessage]) -> [WireMessage] {
    var remaining = existing.filter { $0.role == .user && !$0.attachments.isEmpty }
    return incoming.map { message in
        guard message.role == .user, message.attachments.isEmpty else { return message }
        if let idx = remaining.firstIndex(where: { $0.id == message.id }) {
            let source = remaining.remove(at: idx)
            return preserveUserAttachments(existing: source, incoming: message)
        }
        if let idx = remaining.firstIndex(where: { isLikelySameUserPrompt($0.content, message.content) }) {
            let source = remaining.remove(at: idx)
            return preserveUserAttachments(existing: source, incoming: message)
        }
        return message
    }
}

private func preserveUserAttachments(existing: WireMessage, incoming: WireMessage) -> WireMessage {
    guard incoming.role == .user,
          incoming.attachments.isEmpty,
          !existing.attachments.isEmpty
    else { return incoming }
    return WireMessage(
        id: incoming.id,
        role: incoming.role,
        content: incoming.content,
        reasoningText: incoming.reasoningText,
        streamingFinished: incoming.streamingFinished,
        isError: incoming.isError,
        timestamp: incoming.timestamp,
        timeline: incoming.timeline,
        workSummary: incoming.workSummary,
        audioRef: incoming.audioRef ?? existing.audioRef,
        attachments: existing.attachments
    )
}

private func isLikelySameUserPrompt(_ lhs: String, _ rhs: String) -> Bool {
    let left = normalizedPrompt(lhs)
    let right = normalizedPrompt(rhs)
    guard !left.isEmpty, !right.isEmpty else { return false }
    return left == right || left.hasSuffix(right) || right.hasSuffix(left)
}

private func normalizedPrompt(_ text: String) -> String {
    var value = text.trimmingCharacters(in: .whitespacesAndNewlines)
    let labels = ["[image fallback]", "[image]", "[images]"]
    for label in labels where value.hasPrefix(label) {
        value = String(value.dropFirst(label.count)).trimmingCharacters(in: .whitespacesAndNewlines)
        break
    }
    if value.hasPrefix("Attached images are preserved in Clawix UI,"),
       let range = value.range(of: "\n\n") {
        value = String(value[range.upperBound...]).trimmingCharacters(in: .whitespacesAndNewlines)
    }
    return value
}

private struct MutableSnapshot {
    var chat: WireSession
    var messages: [WireMessage]

    init(_ snapshot: BridgeChatSnapshot) {
        self.chat = snapshot.chat
        self.messages = snapshot.messages
    }

    var snapshot: BridgeChatSnapshot {
        BridgeChatSnapshot(chat: chat, messages: messages)
    }
}
