import Foundation

// Resolves conversation titles from runtime metadata. Aggregates two sources
// of truth that both use the same `{id, thread_name, updated_at}` line
// format:
//
//   1. The runtime session index (read-only).
//   2. This app's Application Support folder.
//      session_titles.jsonl         (read-write: where we persist titles
//      generated by TitleGenerator)
//
// Both are append-only JSONL; latest entry per id wins on a fold pass.
// Manual renames done from inside this app live in AppMetadataStore
// (`chatTitleByThread`) and are NOT consulted here. Callers layer them
// on top of whatever this store returns.

@MainActor
final class SessionTitleStore {

    struct Entry {
        let id: String
        let threadName: String
        let updatedAt: Date
        let source: String?
    }

    private static let backendDirectoryName = ".codex"

    static var backendIndexURL: URL {
        FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("\(backendDirectoryName)/session_index.jsonl")
    }

    static var overridesURL: URL {
        let base: URL
        if let dir = try? FileManager.default.url(
            for: .applicationSupportDirectory,
            in: .userDomainMask,
            appropriateFor: nil,
            create: true
        ) {
            base = dir
        } else {
            base = FileManager.default.homeDirectoryForCurrentUser
                .appendingPathComponent("Library/Application Support", isDirectory: true)
        }
        let dir = base.appendingPathComponent(appPrefsSuite, isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir.appendingPathComponent("session_titles.jsonl")
    }

    private var resolved: [String: Entry] = [:]

    init() {
        reload()
    }

    /// Re-fold both files into the in-memory table. Cheap (linear scan
    /// of a few hundred KiB max), safe to call on app start and on demand.
    func reload() {
        var fold: [String: Entry] = [:]
        merge(file: Self.backendIndexURL, into: &fold, defaultSource: "runtime")
        merge(file: Self.overridesURL, into: &fold, defaultSource: "generated")
        resolved = fold
    }

    func title(for id: String) -> String? {
        guard let entry = resolved[id] else { return nil }
        let trimmed = entry.threadName.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? nil : trimmed
    }

    func hasTitle(for id: String) -> Bool { title(for: id) != nil }

    /// Append a generated title to our overrides JSONL and update the
    /// in-memory table. No-ops on empty input. Safe across crashes
    /// because writes are append-only with line granularity.
    func persistGenerated(id: String, title: String) {
        let trimmed = title.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }

        let now = Date()
        let iso = ISO8601DateFormatter()
        iso.formatOptions = [.withInternetDateTime, .withFractionalSeconds]

        let payload: [String: Any] = [
            "id": id,
            "thread_name": trimmed,
            "updated_at": iso.string(from: now),
            "source": "generated"
        ]
        guard let data = try? JSONSerialization.data(withJSONObject: payload),
              var line = String(data: data, encoding: .utf8) else { return }
        line.append("\n")

        let url = Self.overridesURL
        if FileManager.default.fileExists(atPath: url.path) {
            if let handle = try? FileHandle(forWritingTo: url) {
                defer { try? handle.close() }
                _ = try? handle.seekToEnd()
                if let bytes = line.data(using: .utf8) {
                    try? handle.write(contentsOf: bytes)
                }
            }
        } else {
            try? line.data(using: .utf8)?.write(to: url, options: .atomic)
        }

        resolved[id] = Entry(id: id, threadName: trimmed, updatedAt: now, source: "generated")
    }

    private func merge(file: URL, into fold: inout [String: Entry], defaultSource: String) {
        guard let data = try? Data(contentsOf: file) else { return }
        let isoMain = ISO8601DateFormatter()
        isoMain.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        let isoFallback = ISO8601DateFormatter()
        isoFallback.formatOptions = [.withInternetDateTime]

        var start = data.startIndex
        while start < data.endIndex {
            let nl = data[start...].firstIndex(of: 0x0a) ?? data.endIndex
            let line = data[start..<nl]
            start = nl < data.endIndex ? data.index(after: nl) : data.endIndex
            if line.isEmpty { continue }
            guard let obj = (try? JSONSerialization.jsonObject(with: line, options: [])) as? [String: Any],
                  let id = obj["id"] as? String,
                  let name = obj["thread_name"] as? String else { continue }
            let updatedAtStr = obj["updated_at"] as? String ?? ""
            let updatedAt = isoMain.date(from: updatedAtStr)
                ?? isoFallback.date(from: updatedAtStr)
                ?? .distantPast
            let source = (obj["source"] as? String) ?? defaultSource
            let candidate = Entry(id: id, threadName: name, updatedAt: updatedAt, source: source)
            if let existing = fold[id], existing.updatedAt >= candidate.updatedAt { continue }
            fold[id] = candidate
        }
    }
}
